import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frCoalConfig = new BraidingItem({
  id: 38,
  code: '030',
  name: '煤',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '物資經濟動員方案',
  mobilizationPlanId: 3,
  mobilizationClassification: '煤',
  mobilizationClassificationId: 24,
  firstLevelAgency: '經濟部',
  firstLevelAgencyId: '',
  secondaryAgency: '能源署',
  secondaryAgencyId: '',

  searchKey: 'storageName',

  fetchDetailData: (id) => ApiService.frCoal.readFrCoalById(id),
  fetchCategoryData: ApiService.frCoal.readFrCoalPagination,
  queryCategoryData: ApiService.frCoal.readFrCoalQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '代表(所有)人',
      keyList: [
        new KeyListItem({ key: 'name', keyTitle: '姓名' }),
        new KeyListItem({ key: 'tel', keyTitle: '聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '所有單位(管理機關)',
      keyList: [
        new KeyListItem({ key: 'companyName', keyTitle: '公司名稱' }),
        new KeyListItem({ key: 'companyTel', keyTitle: '學校電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '物資資訊',
      keyList: [
        new KeyListItem({ key: 'type', keyTitle: '種類' }),
        new KeyListItem({ key: 'storageName', keyTitle: '儲存設施名稱' }),
        new KeyListItem({ key: 'facilityAddress', keyTitle: '設施地址' }),
        new KeyListItem({ key: 'facilityCity', keyTitle: '廠商縣市別' }),
        new KeyListItem({ key: 'facilityTown', keyTitle: '廠商鄉鎮市區別' }),
        new KeyListItem({ key: 'facilityVillage', keyTitle: '廠商村里別' }),
        new KeyListItem({ key: 'stock', keyTitle: '存量' }),
        new KeyListItem({ key: 'stockDays', keyTitle: '存量天數' }),
        new KeyListItem({ key: 'maxstock', keyTitle: '最大存量' }),
        new KeyListItem({ key: 'maxstockDays', keyTitle: '最大存量天數' }),
        new KeyListItem({ key: 'dailyUsage', keyTitle: '每日用量' }),
        new KeyListItem({ key: 'safetyStock', keyTitle: '安全存量' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '儲存設施名稱',
      accessor: 'storageName',
    },
    {
      Header: '設施地址',
      accessor: 'facilityAddress',
    },
    {
      Header: '每日用量',
      accessor: 'dailyUsage',
    },
    {
      Header: '安全存量',
      accessor: 'safetyStock',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '姓名',
      englishField: 'name',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 3,
      chineseField: '聯絡電話',
      englishField: 'tel',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 30,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 4,
      chineseField: '公司名稱',
      englishField: 'company_name',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 50,
      remark: '',
    },
    {
      id: 5,
      chineseField: '公司聯絡電話',
      englishField: 'company_tel',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 30,
      remark: '',
    },
    {
      id: 6,
      chineseField: '種類',
      englishField: 'type',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 30,
      remark: '',
    },
    {
      id: 7,
      chineseField: '儲存設施名稱',
      englishField: 'storage_name',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 8,
      chineseField: '設施地址',
      englishField: 'facility_address',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 9,
      chineseField: '廠商縣市別',
      englishField: 'facility_city',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 10,
      chineseField: '廠商鄉鎮市區別',
      englishField: 'facility_town',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 11,
      chineseField: '廠商村里別',
      englishField: 'facility_village',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 12,
      chineseField: '廠商y坐標',
      englishField: 'facility_y',
      dataType: '物資資訊',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 13,
      chineseField: '廠商x坐標',
      englishField: 'facility_x',
      dataType: '物資資訊',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 14,
      chineseField: '存量',
      englishField: 'stock',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark: '【必填】\n計量單位(萬噸)',
    },
    {
      id: 15,
      chineseField: '存量天數',
      englishField: 'stock_days',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark: '【必填】',
    },
    {
      id: 16,
      chineseField: '最大存量',
      englishField: 'maxstock',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark: '【必填】\n計量單位(萬噸)',
    },
    {
      id: 17,
      chineseField: '最大存量天數',
      englishField: 'maxstock_days',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark: '【必填】',
    },
    {
      id: 18,
      chineseField: '每日用量',
      englishField: 'daily_usage',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark: '【系統判斷】\n依「存量」/「存量天數」分析「每日用量」',
    },
    {
      id: 19,
      chineseField: '安全存量',
      englishField: 'safety_stock',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark: '【系統判斷】\n系統內部設定法定煤安全存量天數【30天】',
    },
    {
      id: 20,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 21,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 22,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 23,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 24,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 25,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 26,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 27,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 28,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 29,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frCoalConfig;
