import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frOilConfig = new BraidingItem({
  id: 39,
  code: '031',
  name: '油',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '物資經濟動員方案',
  mobilizationPlanId: 3,
  mobilizationClassification: '油氣',
  mobilizationClassificationId: 25,
  firstLevelAgency: '經濟部',
  firstLevelAgencyId: '',
  secondaryAgency: '能源署',
  secondaryAgencyId: '',

  searchKey: 'unitName',

  fetchDetailData: (id) => ApiService.frOil.readFrOilById(id),
  fetchCategoryData: ApiService.frOil.readFrOilPagination,
  queryCategoryData: ApiService.frOil.readFrOilQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '所有單位',
      keyList: [new KeyListItem({ key: 'unitName', keyTitle: '單位名稱' })],
    }),
    new ConfigListItem({
      sectionTitle: '物資資訊',
      keyList: [
        new KeyListItem({ key: 'type', keyTitle: '種類' }),
        new KeyListItem({ key: 'stock', keyTitle: '儲存量' }),
        new KeyListItem({ key: 'storageDay', keyTitle: '儲存日數' }),
        new KeyListItem({ key: 'storageFacility', keyTitle: '儲槽設施' }),
        new KeyListItem({ key: 'storageCity', keyTitle: '儲槽地區' }),
        new KeyListItem({ key: 'safetyStock', keyTitle: '安全存量' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '單位名稱',
      accessor: 'unitName',
    },
    {
      Header: '儲存量',
      accessor: 'stock',
    },
    {
      Header: '儲槽地區',
      accessor: 'storageCity',
    },
    {
      Header: '安全存量',
      accessor: 'safetyStock',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '單位名稱',
      englishField: 'unit_name',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】\n區分台灣中油公司、台塑石化公司、經濟部能源局',
    },
    {
      id: 3,
      chineseField: '種類',
      englishField: 'type',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 4,
      chineseField: '儲存量',
      englishField: 'stock',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark: '【必填】公秉',
    },
    {
      id: 5,
      chineseField: '儲存日數',
      englishField: 'storage_day',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark: '【必填】天',
    },
    {
      id: 6,
      chineseField: '儲槽設施',
      englishField: 'storage_facility',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】座',
    },
    {
      id: 7,
      chineseField: '儲槽地區',
      englishField: 'storage_city',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 400,
      remark: '',
    },
    {
      id: 8,
      chineseField: 'y坐標',
      englishField: 'city_y',
      dataType: '物資資訊',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 9,
      chineseField: 'x坐標',
      englishField: 'city_x',
      dataType: '物資資訊',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 10,
      chineseField: '安全存量',
      englishField: 'safety_stock',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark:
        '【系統判斷】\n情境1.由系統依本編管類別【種類】欄位內容屬「民間儲油」者，回饋本欄位安全存量天數【60天】\n情境2.由系統依本編管類別【種類】欄位內容屬「政府儲油」者，回饋本欄位安全存量天數【30天】',
    },
    {
      id: 11,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 12,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 13,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 14,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 15,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 16,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 17,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 18,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 19,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 20,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frOilConfig;
