import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frRFEquipConfig = new BraidingItem({
  id: 29,
  code: '021',
  name: '射頻器材',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '交通動員方案',
  mobilizationPlanId: 2,
  mobilizationClassification: '通信',
  mobilizationClassificationId: 19,
  firstLevelAgency: '通傳會',
  firstLevelAgencyId: '',
  secondaryAgency: '',
  secondaryAgencyId: '',

  searchKey: 'factoryName',

  fetchDetailData: (id) => ApiService.frRFEquip.readFrRfEquipById(id),
  fetchCategoryData: ApiService.frRFEquip.readFrRfEquipPagination,
  queryCategoryData: ApiService.frRFEquip.readFrRfEquipQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '代表(所有)人',
      keyList: [
        new KeyListItem({ key: 'name', keyTitle: '姓名' }),
        new KeyListItem({ key: 'birthdate', keyTitle: '出生年月日' }),
        new KeyListItem({ key: 'gender', keyTitle: '性別' }),
        new KeyListItem({ key: 'pid', keyTitle: '身分證字號' }),
        new KeyListItem({ key: 'abode', keyTitle: '居住所' }),
        new KeyListItem({ key: 'abodeCity', keyTitle: '居住縣市別' }),
        new KeyListItem({ key: 'abodeTown', keyTitle: '居住鄉鎮市區別' }),
        new KeyListItem({ key: 'abodeVillage', keyTitle: '居住村里別' }),
        new KeyListItem({ key: 'tel', keyTitle: '聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '所有單位',
      keyList: [
        new KeyListItem({ key: 'factoryName', keyTitle: '廠商名稱' }),
        new KeyListItem({ key: 'factoryAddress', keyTitle: '廠商地址' }),
        new KeyListItem({ key: 'factoryCity', keyTitle: '廠商縣市別' }),
        new KeyListItem({ key: 'factoryTown', keyTitle: '廠商鄉鎮市區別' }),
        new KeyListItem({ key: 'factoryVillage', keyTitle: '廠商村里別' }),
        new KeyListItem({ key: 'factoryTel', keyTitle: '廠商聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '物資項量',
      keyList: [
        new KeyListItem({ key: 'approvalno', keyTitle: '審定號碼' }),
        new KeyListItem({ key: 'approvalDate', keyTitle: '審定日期' }),
        new KeyListItem({ key: 'workFrequency', keyTitle: '工作頻率' }),
        new KeyListItem({ key: 'useFrequency', keyTitle: '使用頻率' }),
        new KeyListItem({ key: 'brand', keyTitle: '廠牌' }),
        new KeyListItem({ key: 'model', keyTitle: '型號' }),
        new KeyListItem({ key: 'itemtype', keyTitle: '品項類別' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '徵購徵用',
      keyList: [
        new KeyListItem({ key: 'levyApprovalno', keyTitle: '審定號碼' }),
        new KeyListItem({ key: 'levyType', keyTitle: '徵用類別' }),
        new KeyListItem({ key: 'levyUnit', keyTitle: '徵用機關' }),
        new KeyListItem({ key: 'levyPlace', keyTitle: '徵用地點' }),
        new KeyListItem({ key: 'levyCity', keyTitle: '徵用縣市別' }),
        new KeyListItem({ key: 'levyTown', keyTitle: '徵用鄉鎮市區別' }),
        new KeyListItem({ key: 'levyVillage', keyTitle: '徵用村里別' }),
        new KeyListItem({ key: 'levyTime', keyTitle: '徵用時間' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '廠商名稱',
      accessor: 'factoryName',
    },
    {
      Header: '廠商地址',
      accessor: 'factoryAddress',
    },
    {
      Header: '徵用機關',
      accessor: 'levyUnit',
    },
    {
      Header: '徵用地點',
      accessor: 'levyPlace',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '代表人(所有人)姓名',
      englishField: 'name',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark:
        '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 3,
      chineseField: '出生年月日',
      englishField: 'birthdate',
      dataType: '代表(所有)人',
      type: 'datetime',
      length: '',
      remark: '民國年7碼',
    },
    {
      id: 4,
      chineseField: '性別',
      englishField: 'gender',
      dataType: '代表(所有)人',
      type: 'int',
      length: '',
      remark: '性別判斷依身分證第二碼判斷：1、8為男性、2、9為女性',
    },
    {
      id: 5,
      chineseField: '身分證字號',
      englishField: 'pid',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 20,
      remark:
        '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽',
    },
    {
      id: 6,
      chineseField: '居住所',
      englishField: 'abode',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '完整地址',
    },
    {
      id: 7,
      chineseField: '居住縣市別',
      englishField: 'abode_city',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 8,
      chineseField: '居住鄉鎮市區別',
      englishField: 'abode_town',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 9,
      chineseField: '居住村里別',
      englishField: 'abode_village',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 10,
      chineseField: '居住y坐標',
      englishField: 'abode_y',
      dataType: '代表(所有)人',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 11,
      chineseField: '居住x坐標',
      englishField: 'abode_x',
      dataType: '代表(所有)人',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 12,
      chineseField: '聯絡電話',
      englishField: 'tel',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 30,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 13,
      chineseField: '廠商名稱',
      englishField: 'factory_name',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 50,
      remark: '送審廠商',
    },
    {
      id: 14,
      chineseField: '廠商地址',
      englishField: 'factory_address',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 15,
      chineseField: '廠商縣市別',
      englishField: 'factory_city',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 16,
      chineseField: '廠商鄉鎮市區別',
      englishField: 'factory_town',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 17,
      chineseField: '廠商村里別',
      englishField: 'factory_village',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 18,
      chineseField: '廠商y坐標',
      englishField: 'factory_y',
      dataType: '所有單位',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 19,
      chineseField: '廠商x坐標',
      englishField: 'factory_x',
      dataType: '所有單位',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 20,
      chineseField: '廠商聯絡電話',
      englishField: 'factory_tel',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 30,
      remark: '',
    },
    {
      id: 21,
      chineseField: '審定號碼',
      englishField: 'approvalno',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 22,
      chineseField: '審定日期',
      englishField: 'approvaldate',
      dataType: '物資項量',
      type: 'datetime',
      length: '',
      remark: '民國7碼',
    },
    {
      id: 23,
      chineseField: '工作頻率',
      englishField: 'work_frequency',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 800,
      remark: '',
    },
    {
      id: 24,
      chineseField: '使用頻率',
      englishField: 'use_frequency',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 800,
      remark: '',
    },
    {
      id: 25,
      chineseField: '廠牌',
      englishField: 'brand',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 50,
      remark: '',
    },
    {
      id: 26,
      chineseField: '型號',
      englishField: 'model',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 50,
      remark: '',
    },
    {
      id: 27,
      chineseField: '品項類別',
      englishField: 'itemtype',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】',
    },
    {
      id: 28,
      chineseField: '供應能量',
      englishField: 'supply_quanity',
      dataType: '物資項量',
      type: 'int',
      length: '',
      remark: '',
    },
    {
      id: 29,
      chineseField: '計量單位',
      englishField: 'supply_unit',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 50,
      remark: '',
    },
    {
      id: '【以下資料由後備指揮部另檔提供】',
      chineseField: '',
      englishField: '',
      dataType: '',
      type: '',
      length: '',
      remark: '',
    },
    {
      id: 30,
      chineseField: '徵用審定號碼',
      englishField: 'levy_approvalno',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】勾稽比對欄位',
    },
    {
      id: 31,
      chineseField: '徵購類別',
      englishField: 'levy_type',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】',
    },
    {
      id: 32,
      chineseField: '徵購機關',
      englishField: 'levy_unit',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 33,
      chineseField: '徵購地點',
      englishField: 'levy_place',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 34,
      chineseField: '徵用縣市別',
      englishField: 'levy_city',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 35,
      chineseField: '徵用鄉鎮市區別',
      englishField: 'levy_town',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 36,
      chineseField: '徵用村里別',
      englishField: 'levy_village',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 37,
      chineseField: '徵用y坐標',
      englishField: 'levy_y',
      dataType: '徵購徵用',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 38,
      chineseField: '徵用x坐標',
      englishField: 'levy_x',
      dataType: '徵購徵用',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 39,
      chineseField: '徵用時間',
      englishField: 'levy_time',
      dataType: '徵購徵用',
      type: 'datetime',
      length: '',
      remark: '民國年7碼',
    },
    {
      id: 40,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 41,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 42,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 43,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 44,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 45,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 46,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 47,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 48,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 49,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frRFEquipConfig;
