import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';
import HrHeavymachinerydriverPlanResponse from '../../../dataModels/HrHeavymachinerydriverPlan/HrHeavymachinerydriverPlanResponse';

const hrHeavymachinerydriverConfig = new BraidingItem({
  id: 24,
  code: '017',
  name: '工程重機械操作人員',
  type: '人力',
  typeIndex: '1',
  mobilizationPlan: '交通動員方案',
  mobilizationPlanId: 2,
  mobilizationClassification: '工程重機械',
  mobilizationClassificationId: 17,
  firstLevelAgency: '內政部',
  firstLevelAgencyId: '',
  secondaryAgency: '國土署',
  secondaryAgencyId: '',

  fetchDetailData: (id) =>
    ApiService.hrHeavymachinerydriver.readHrHeavymachinerydriverById(id),
  fetchCategoryData:
    ApiService.hrHeavymachinerydriver.readHrHeavymachinerydriverPagination,
  queryCategoryData:
    ApiService.hrHeavymachinerydriver.readHrHeavymachinerydriverQueryPagination,
  fetchPlanData: ({ pid }) =>
    ApiService.hrHeavymachinerydriverPlan.readHrHeavymachinerydriverPlanByPid(
      pid,
    ),

  planDataModel: HrHeavymachinerydriverPlanResponse,

  fetchUniqueDetailData: (id) =>
    ApiService.hrHeavymachinerydriver.readUniqueHrHeavymachinerydriverById(id),
  fetchUniqueCategoryData:
    ApiService.hrHeavymachinerydriver
      .readUniqueHrHeavymachinerydriverPagination,
  queryUniqueCategoryData:
    ApiService.hrHeavymachinerydriver
      .readUniqueHrHeavymachinerydriverQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '基本資料',
      keyList: [
        new KeyListItem({ key: 'name', keyTitle: '姓名' }),
        new KeyListItem({ key: 'birthdate', keyTitle: '出生年月日' }),
        new KeyListItem({ key: 'pid', keyTitle: '身分證字號' }),
        new KeyListItem({ key: 'gender', keyTitle: '性別' }),
        new KeyListItem({ key: 'habitation', keyTitle: '戶籍地' }),
        new KeyListItem({ key: 'habitatCity', keyTitle: '戶籍縣市別' }),
        new KeyListItem({ key: 'habitatTown', keyTitle: '戶籍鄉鎮市區別' }),
        new KeyListItem({ key: 'habitatVillage', keyTitle: '戶籍村里別' }),
        new KeyListItem({ key: 'abode', keyTitle: '居住所' }),
        new KeyListItem({ key: 'abodeCity', keyTitle: '居住縣市別' }),
        new KeyListItem({ key: 'abodeTown', keyTitle: '居住鄉鎮市區別' }),
        new KeyListItem({ key: 'abodeVillage', keyTitle: '居住村里別' }),
        new KeyListItem({ key: 'tel', keyTitle: '聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '編管資料',
      keyList: [
        new KeyListItem({ key: 'manageType', keyTitle: '編管類型' }),
        new KeyListItem({ key: 'manageUnit', keyTitle: '編管機構' }),
        new KeyListItem({ key: 'managePlace', keyTitle: '編管地點' }),
        new KeyListItem({ key: 'manageCity', keyTitle: '編管縣市別' }),
        new KeyListItem({ key: 'manageTown', keyTitle: '編管鄉鎮市區別' }),
        new KeyListItem({ key: 'manageVillage', keyTitle: '編管村里別' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '人力資訊',
      keyList: [
        new KeyListItem({ key: 'updatedateString', keyTitle: '異動時間' }),
        new KeyListItem({ key: 'skill', keyTitle: '專長類別' }),
        new KeyListItem({ key: 'unit', keyTitle: '任職單位' }),
        new KeyListItem({ key: 'lic', keyTitle: '證照' }),
      ],
    }),
  ],
  planConfigList: [
    new ConfigListItem({
      sectionTitle: '動員演訓(徵用情形)',
      keyList: [
        new KeyListItem({ key: 'planType', keyTitle: '演訓類別' }),
        new KeyListItem({ key: 'planStart', keyTitle: '演訓時間(起)' }),
        new KeyListItem({ key: 'planEnd', keyTitle: '演訓時間(迄)' }),
        new KeyListItem({ key: 'planPlace', keyTitle: '演訓地點' }),
        new KeyListItem({ key: 'planCity', keyTitle: '演訓縣市別' }),
        new KeyListItem({ key: 'planTown', keyTitle: '演訓鄉鎮市區別' }),
        new KeyListItem({ key: 'planVillage', keyTitle: '演訓村里別' }),
        new KeyListItem({ key: 'levyUnit', keyTitle: '徵用機關' }),
        new KeyListItem({ key: 'levySkill', keyTitle: '徵用專長' }),
      ],
    }),
  ],
  categoryTableHeader: [
    {
      Header: '姓名',
      accessor: 'name',
    },
    {
      Header: '身分證字號',
      accessor: 'pid',
    },
    {
      Header: '編管類型',
      accessor: 'manageType',
    },
    {
      Header: '編管機構',
      accessor: 'manageUnit',
    },
    {
      Header: '編管地點',
      accessor: 'managePlace',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '姓名',
      englishField: 'name',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 200,
      remark:
        '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 3,
      chineseField: '出生年月日',
      englishField: 'birthdate',
      dataType: '基本資料',
      type: 'datetime',
      length: '',
      remark: '【必填】民國年7碼',
    },
    {
      id: 4,
      chineseField: '性別',
      englishField: 'gender',
      dataType: '基本資料',
      type: 'int',
      length: '',
      remark: '性別判斷依身分證第二碼判斷：1、8為男性、2、9為女性',
    },
    {
      id: 5,
      chineseField: '身分證字號',
      englishField: 'pid',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 20,
      remark:
        '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽',
    },
    {
      id: 6,
      chineseField: '戶籍地',
      englishField: 'habitation',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 200,
      remark: '完整地址',
    },
    {
      id: 7,
      chineseField: '戶籍縣市別',
      englishField: 'habitat_city',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 8,
      chineseField: '戶籍鄉鎮市區別',
      englishField: 'habitat_town',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 9,
      chineseField: '戶籍村里別',
      englishField: 'habitat_village',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 10,
      chineseField: '戶籍y坐標',
      englishField: 'habitat_y',
      dataType: '基本資料',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 11,
      chineseField: '戶籍x坐標',
      englishField: 'habitat_x',
      dataType: '基本資料',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 12,
      chineseField: '居住所',
      englishField: 'abode',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 13,
      chineseField: '居住縣市別',
      englishField: 'abode_city',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 14,
      chineseField: '居住鄉鎮市區別',
      englishField: 'abode_town',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 15,
      chineseField: '居住村里別',
      englishField: 'abode_village',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 16,
      chineseField: '居住y坐標',
      englishField: 'abode_y',
      dataType: '基本資料',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 17,
      chineseField: '居住x坐標',
      englishField: 'abode_x',
      dataType: '基本資料',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 18,
      chineseField: '聯絡電話',
      englishField: 'tel',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 30,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 19,
      chineseField: '編管類型',
      englishField: 'manage_type',
      dataType: '編管資料',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】\n專職操作人員、職業公(工)會會員、志願登記人員',
    },
    {
      id: 20,
      chineseField: '編管機構',
      englishField: 'manage_unit',
      dataType: '編管資料',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】\n縣市工務單位',
    },
    {
      id: 21,
      chineseField: '編管地點',
      englishField: 'manage_place',
      dataType: '編管資料',
      type: 'nvarchar',
      length: 200,
      remark:
        '【必填】\n專職操作人員填寫任職單位地址、公會與志願者填寫個人地址',
    },
    {
      id: 22,
      chineseField: '編管縣市別',
      englishField: 'manage_city',
      dataType: '編管資料',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 23,
      chineseField: '編管鄉鎮市區別',
      englishField: 'manage_town',
      dataType: '編管資料',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 24,
      chineseField: '編管村里別',
      englishField: 'manage_village',
      dataType: '編管資料',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 25,
      chineseField: '編管y坐標',
      englishField: 'manage_y',
      dataType: '編管資料',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 26,
      chineseField: '編管x坐標',
      englishField: 'manage_x',
      dataType: '編管資料',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 27,
      chineseField: '異動時間',
      englishField: 'updatedate',
      dataType: '人力資訊',
      type: 'datetime',
      length: '',
      remark: '系統判斷',
    },
    {
      id: 28,
      chineseField: '專長類別',
      englishField: 'skill',
      dataType: '人力資訊',
      type: 'nvarchar',
      length: 1000,
      remark:
        '【必填】\n1.可多筆專長資料輸入\n2.【BI】儀表板-編管指標：分析以1對多人次列計',
    },
    {
      id: 29,
      chineseField: '任職單位',
      englishField: 'unit',
      dataType: '人力資訊',
      type: 'nvarchar',
      length: 50,
      remark: '單位名稱',
    },
    {
      id: 30,
      chineseField: '證照',
      englishField: 'lic',
      dataType: '人力資訊',
      type: 'nvarchar',
      length: 1000,
      remark: '',
    },
    {
      id: 31,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 32,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 33,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 34,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 35,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 36,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 37,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 38,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 39,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 40,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default hrHeavymachinerydriverConfig;
