import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frVeteranshomesConfig = new BraidingItem({
  id: 11,
  code: '007',
  name: '國軍退除役官兵輔導委員會榮家安養機構',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '人力動員方案',
  mobilizationPlanId: 1,
  mobilizationClassification: '戰時受傷及退除役軍人安置',
  mobilizationClassificationId: 8,
  firstLevelAgency: '退輔會',
  firstLevelAgencyId: '',
  secondaryAgency: '',
  secondaryAgencyId: '',

  fetchDetailData: (id) =>
    ApiService.frVeteranshomes.readFrVeteranshomesById(id),
  fetchCategoryData: ApiService.frVeteranshomes.readFrVeteranshomesPagination,
  queryCategoryData:
    ApiService.frVeteranshomes.readFrVeteranshomesQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '代表(所有)人',
      keyList: [
        new KeyListItem({ key: 'name', keyTitle: '姓名' }),
        new KeyListItem({ key: 'title', keyTitle: '職稱' }),
        new KeyListItem({ key: 'tel', keyTitle: '聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '所有單位',
      keyList: [
        new KeyListItem({ key: 'orgName', keyTitle: '機構名稱' }),
        new KeyListItem({ key: 'orgAddress', keyTitle: '機構地址' }),
        new KeyListItem({ key: 'orgCity', keyTitle: '機構縣市別' }),
        new KeyListItem({ key: 'orgTown', keyTitle: '機構鄉鎮市區別' }),
        new KeyListItem({ key: 'orgVillage', keyTitle: '機構村里別' }),
        new KeyListItem({ key: 'orgTel', keyTitle: '機構聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '物資資訊',
      keyList: [
        new KeyListItem({ key: 'regBedNo', keyTitle: '規定床位' }),
        new KeyListItem({ key: 'occNo', keyTitle: '安置人數' }),
        new KeyListItem({ key: 'occRate', keyTitle: '安置率' }),
        new KeyListItem({ key: 'adjustBedNo', keyTitle: '增加床位' }),
        new KeyListItem({ key: 'wartmagBedNo', keyTitle: '戰時管用床位' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '姓名',
      accessor: 'name',
    },
    {
      Header: '機構名稱',
      accessor: 'orgName',
    },
    {
      Header: '規定床位',
      accessor: 'regBedNo',
    },
    {
      Header: '安置人數',
      accessor: 'occNo',
    },
    {
      Header: '戰時管用床位',
      accessor: 'wartmagBedNo',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '姓名',
      englishField: 'name',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 3,
      chineseField: '職稱',
      englishField: 'title',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 30,
      remark: '',
    },
    {
      id: 4,
      chineseField: '聯絡電話',
      englishField: 'tel',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 30,
      remark: '',
    },
    {
      id: 5,
      chineseField: '機構名稱',
      englishField: 'org_name',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】完整',
    },
    {
      id: 6,
      chineseField: '機構地址',
      englishField: 'org_address',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 7,
      chineseField: '機構縣市別',
      englishField: 'org_city',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 8,
      chineseField: '機構鄉鎮市區別',
      englishField: 'org_town',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 9,
      chineseField: '機構村里別',
      englishField: 'org_village',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 10,
      chineseField: '機構y坐標',
      englishField: 'org_y',
      dataType: '所有單位',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 11,
      chineseField: '機構x坐標',
      englishField: 'org_x',
      dataType: '所有單位',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 12,
      chineseField: '機構聯絡電話',
      englishField: 'org_tel',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 30,
      remark: '',
    },
    {
      id: 13,
      chineseField: '平時規定床位',
      englishField: 'reg_bed_no',
      dataType: '物資資訊',
      type: 'int',
      length: '',
      remark: '【必填】平時規定床位',
    },
    {
      id: 14,
      chineseField: '平時安置人數',
      englishField: 'reg_occ_no',
      dataType: '物資資訊',
      type: 'int',
      length: '',
      remark: '【必填】安置人數',
    },
    {
      id: 15,
      chineseField: '戰時整備床位',
      englishField: 'wartmag_bed_no',
      dataType: '物資資訊',
      type: 'int',
      length: '',
      remark: '【必填】最大床位數',
    },
    {
      id: 16,
      chineseField: '戰時安置人數',
      englishField: 'wartmag_occ_no',
      dataType: '物資資訊',
      type: 'int',
      length: '',
      remark: '【必填】最大安置人數',
    },
    {
      id: 17,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 18,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 19,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 20,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 21,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 22,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 23,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 24,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 25,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 26,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frVeteranshomesConfig;
