import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';
import HrMedicalmanPlanResponse from '../../../dataModels/HrMedicalmanPlan/HrMedicalmanPlanResponse';

const hrMedicalmanConfig = new BraidingItem({
  id: 54,
  code: '044',
  name: '醫事人力',
  type: '人力',
  typeIndex: '1',
  mobilizationPlan: '衛生動員方案',
  mobilizationPlanId: 8,
  mobilizationClassification: '醫政',
  mobilizationClassificationId: 53,
  firstLevelAgency: '衛福部',
  firstLevelAgencyId: '',
  secondaryAgency: '醫事司',
  secondaryAgencyId: '',

  fetchDetailData: (id) => ApiService.hrMedicalman.readHrMedicalmanById(id),
  fetchCategoryData: ApiService.hrMedicalman.readHrMedicalmanPagination,
  queryCategoryData: ApiService.hrMedicalman.readHrMedicalmanQueryPagination,
  fetchPlanData: ({ pid }) =>
    ApiService.hrMedicalmanPlan.readHrMedicalmanPlanByPid(pid),

  planDataModel: HrMedicalmanPlanResponse,

  fetchUniqueDetailData: (id) =>
    ApiService.hrMedicalman.readUniqueHrMedicalmanById(id),
  fetchUniqueCategoryData:
    ApiService.hrMedicalman.readUniqueHrMedicalmanPagination,
  queryUniqueCategoryData:
    ApiService.hrMedicalman.readUniqueHrMedicalmanQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '基本資料',
      keyList: [
        new KeyListItem({ key: 'name', keyTitle: '姓名' }),
        new KeyListItem({ key: 'birthdate', keyTitle: '出生年月日' }),
        new KeyListItem({ key: 'gender', keyTitle: '性別' }),
        new KeyListItem({ key: 'pid', keyTitle: '身分證字號' }),
        new KeyListItem({ key: 'habitation', keyTitle: '戶籍地' }),
        new KeyListItem({ key: 'habitatCity', keyTitle: '戶籍縣市別' }),
        new KeyListItem({ key: 'habitatTown', keyTitle: '戶籍鄉鎮市區別' }),
        new KeyListItem({ key: 'habitatVillage', keyTitle: '戶籍村里別' }),
        new KeyListItem({ key: 'abode', keyTitle: '居住所' }),
        new KeyListItem({ key: 'abodeCity', keyTitle: '居住縣市別' }),
        new KeyListItem({ key: 'abodeTown', keyTitle: '居住鄉鎮市區別' }),
        new KeyListItem({ key: 'abodeVillage', keyTitle: '居住村里別' }),
        new KeyListItem({ key: 'tel', keyTitle: '聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '編管資料',
      keyList: [
        new KeyListItem({ key: 'manageType', keyTitle: '編管類型' }),
        new KeyListItem({ key: 'manageUnit', keyTitle: '編管機構' }),
        new KeyListItem({ key: 'managePlace', keyTitle: '編管地點' }),
        new KeyListItem({ key: 'manageCity', keyTitle: '編管縣市別' }),
        new KeyListItem({ key: 'manageTown', keyTitle: '編管鄉鎮市區別' }),
        new KeyListItem({ key: 'manageVillage', keyTitle: '編管村里別' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '人力資訊',
      keyList: [
        new KeyListItem({ key: 'updatedateString', keyTitle: '異動時間' }),
        new KeyListItem({ key: 'skill', keyTitle: '專長類別' }),
        new KeyListItem({ key: 'license', keyTitle: '執業登記科別' }),
        new KeyListItem({ key: 'specialty', keyTitle: '專科類別' }),
        new KeyListItem({ key: 'identityDist', keyTitle: '身份區分' }),
        new KeyListItem({ key: 'organType', keyTitle: '編組類型註記' }),
        new KeyListItem({ key: 'organTeam', keyTitle: '編組區分註記' }),
        new KeyListItem({ key: 'organTitle', keyTitle: '編組職稱註記' }),
        new KeyListItem({ key: 'status', keyTitle: '執業狀態' }),
      ],
    }),
  ],
  planConfigList: [
    new ConfigListItem({
      sectionTitle: '動員演訓(徵用情形)',
      keyList: [
        new KeyListItem({ key: 'planType', keyTitle: '演訓類別' }),
        new KeyListItem({ key: 'planStart', keyTitle: '演訓時間(起)' }),
        new KeyListItem({ key: 'planEnd', keyTitle: '演訓時間(迄)' }),
        new KeyListItem({ key: 'planPlace', keyTitle: '演訓地點' }),
        new KeyListItem({ key: 'planCity', keyTitle: '演訓縣市別' }),
        new KeyListItem({ key: 'planTown', keyTitle: '演訓鄉鎮市區別' }),
        new KeyListItem({ key: 'planVillage', keyTitle: '演訓村里別' }),
      ],
    }),
  ],
  categoryTableHeader: [
    {
      Header: '姓名',
      accessor: 'name',
    },
    {
      Header: '身分證字號',
      accessor: 'pid',
    },
    {
      Header: '編管類型',
      accessor: 'manageType',
    },
    {
      Header: '編管機構',
      accessor: 'manageUnit',
    },
    {
      Header: '編管地點',
      accessor: 'managePlace',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '姓名',
      englishField: 'name',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 200,
      remark:
        '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 3,
      chineseField: '出生年月日',
      englishField: 'birthdate',
      dataType: '基本資料',
      type: 'datetime',
      length: '',
      remark: '【必填】民國年7碼',
    },
    {
      id: 4,
      chineseField: '性別',
      englishField: 'gender',
      dataType: '基本資料',
      type: 'int',
      length: '',
      remark: '性別判斷依身分證第二碼判斷：1、8為男性、2、9為女性',
    },
    {
      id: 5,
      chineseField: '身分證字號',
      englishField: 'pid',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 20,
      remark:
        '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.僅可輸入國人身分證字號及外僑統一證號',
    },
    {
      id: 6,
      chineseField: '戶籍地',
      englishField: 'habitation',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 200,
      remark: '完整地址',
    },
    {
      id: 7,
      chineseField: '戶籍縣市別',
      englishField: 'habitat_city',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 8,
      chineseField: '戶籍鄉鎮市區別',
      englishField: 'habitat_town',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 9,
      chineseField: '戶籍村里別',
      englishField: 'habitat_village',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 10,
      chineseField: '戶籍y坐標',
      englishField: 'habitat_y',
      dataType: '基本資料',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 11,
      chineseField: '戶籍x坐標',
      englishField: 'habitat_x',
      dataType: '基本資料',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 12,
      chineseField: '居住所',
      englishField: 'abode',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 200,
      remark: '完整地址',
    },
    {
      id: 13,
      chineseField: '居住縣市別',
      englishField: 'abode_city',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 14,
      chineseField: '居住鄉鎮市區別',
      englishField: 'abode_town',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 15,
      chineseField: '居住村里別',
      englishField: 'abode_village',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 16,
      chineseField: '居住y坐標',
      englishField: 'abode_y',
      dataType: '基本資料',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 17,
      chineseField: '居住x坐標',
      englishField: 'abode_x',
      dataType: '基本資料',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 18,
      chineseField: '聯絡電話',
      englishField: 'tel',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 30,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 19,
      chineseField: '編管類型',
      englishField: 'manage_type',
      dataType: '編管資料',
      type: 'nvarchar',
      length: 30,
      remark:
        '目前屬單一類型，為維持後續系統分析彈性，仍由機關統一填入「醫事人員」',
    },
    {
      id: 20,
      chineseField: '編管機構',
      englishField: 'manage_unit',
      dataType: '編管資料',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】\n醫院、縣市衛生局、其所屬醫療機構',
    },
    {
      id: 21,
      chineseField: '編管機構類別',
      englishField: 'manage_unittype',
      dataType: '編管資料',
      type: 'nvarchar',
      length: 100,
      remark: '編管機構類別',
    },
    {
      id: 22,
      chineseField: '編管地點',
      englishField: 'manage_place',
      dataType: '編管資料',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】\n醫院執業或任職單位所在地',
    },
    {
      id: 23,
      chineseField: '編管縣市別',
      englishField: 'manage_city',
      dataType: '編管資料',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 24,
      chineseField: '編管鄉鎮市區別',
      englishField: 'manage_town',
      dataType: '編管資料',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 25,
      chineseField: '編管村里別',
      englishField: 'manage_village',
      dataType: '編管資料',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 26,
      chineseField: '編管y坐標',
      englishField: 'manage_y',
      dataType: '編管資料',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 27,
      chineseField: '編管x坐標',
      englishField: 'manage_x',
      dataType: '編管資料',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 28,
      chineseField: '異動時間',
      englishField: 'updatedate',
      dataType: '人力資訊',
      type: 'datetime',
      length: '',
      remark: '系統判斷',
    },
    {
      id: 29,
      chineseField: '專長類別',
      englishField: 'skill',
      dataType: '人力資訊',
      type: 'nvarchar',
      length: 1000,
      remark:
        '【必填】\n【BI】儀表板-編管選單分析：排序依西醫師、護理師、士及助產師、士為優先',
    },
    {
      id: 30,
      chineseField: '執業登記科別',
      englishField: 'license',
      dataType: '人力資訊',
      type: 'nvarchar',
      length: 1000,
      remark:
        '1.依「執業登記科別」填入可複數資料\n2.【BI】查詢報表-納入篩選條件分析，提供關鍵字搜尋',
    },
    {
      id: 31,
      chineseField: '專科類別',
      englishField: 'specialty',
      dataType: '人力資訊',
      type: 'nvarchar',
      length: 1000,
      remark:
        '1.依「專科類別」填入可複數資料\n2.【BI】查詢報表-納入篩選條件分析，提供關鍵字搜尋',
    },
    {
      id: 32,
      chineseField: '身份區分',
      englishField: 'identity_dist',
      dataType: '人力資訊',
      type: 'nvarchar',
      length: 50,
      remark:
        '【系統判斷】\n情境1.由系統比對【軍醫人力】之【身分證號】欄位回饋【現役】資料\n情境2.由系統比對【後備軍人】之【身分證號】欄位回饋【備役】資料\n情境3.非屬上述2種情境者，系統回饋【一般】資料',
    },
    {
      id: 33,
      chineseField: '編組類型註記',
      englishField: 'organ_type',
      dataType: '人力資訊',
      type: 'nvarchar',
      length: 50,
      remark: '【系統判斷】\n由系統比對【民防人力】之【編管類型】欄位回饋資料',
    },
    {
      id: 34,
      chineseField: '編組區分註記',
      englishField: 'organ_team',
      dataType: '人力資訊',
      type: 'nvarchar',
      length: 30,
      remark:
        '【系統判斷】\n由系統比對【民防人力】之【編組區分一】欄位回饋資料(三欄組成一欄)',
    },
    {
      id: 35,
      chineseField: '編組職稱註記',
      englishField: 'organ_title',
      dataType: '人力資訊',
      type: 'nvarchar',
      length: 30,
      remark: '【系統判斷】\n由系統比對【民防人力】之【編組職稱】欄位回饋資料',
    },
    {
      id: 36,
      chineseField: '執業狀態',
      englishField: 'status',
      dataType: '人力資訊',
      type: 'nvarchar',
      length: 10,
      remark: '',
    },
    {
      id: 37,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 38,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 39,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 40,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 41,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 42,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 43,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 44,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 45,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 46,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default hrMedicalmanConfig;
