const fr_food = [
  {
    name: 'ID',
    value: 'Id',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    role: undefined,
    column: 30,
  },
  {
    name: '不合規原因',
    value: 'NonComplianceReason',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    verticalAlign: 'top',
    role: undefined,
    column: 225,
  },
  {
    name: '是否刪除(V)',
    value: 'DeletedAt',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    column: 125,
  },
  {
    name: '縣市別',
    value: 'City',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,10}$/,
    column: 75,
    error: "'縣市別'是必要欄位",
    error4: "'縣市別'超過長度",
  },
  {
    name: '公糧業者家數',
    value: 'PublicfoodBusin',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role5: /^\d+$/,
    column: 150,
    error: "'公糧業者家數'是必要欄位",
    error5: "'公糧業者家數'格式錯誤",
  },
  {
    name: '公糧存糧',
    value: 'PublicfoodStock',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role4: /^\d{0,18}(\.\d{0,6})?$/,
    column: 100,
    error: "'公糧存糧'是必要欄位",
    error4: "'公糧存糧'格式錯誤",
  },
  {
    name: '礱碾設施',
    value: 'RollingFacility',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role5: /^\d+$/,
    column: 100,
    error: "'礱碾設施'是必要欄位",
    error5: "'礱碾設施'格式錯誤",
  },
];

export default fr_food;
