import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frFoodConfig = new BraidingItem({
  id: 44,
  code: '036',
  name: '糧食',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '物資經濟動員方案',
  mobilizationPlanId: 3,
  mobilizationClassification: '糧食',
  mobilizationClassificationId: 29,
  firstLevelAgency: '農業部',
  firstLevelAgencyId: '',
  secondaryAgency: '農糧署',
  secondaryAgencyId: '',

  searchKey: 'city',

  fetchDetailData: (id) => ApiService.frFood.readFrFoodById(id),
  fetchCategoryData: ApiService.frFood.readFrFoodPagination,
  queryCategoryData: ApiService.frFood.readFrFoodQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '所有單位(管理機關)',
      keyList: [new KeyListItem({ key: 'city', keyTitle: '縣市別' })],
    }),
    new ConfigListItem({
      sectionTitle: '物資資訊',
      keyList: [
        new KeyListItem({ key: 'publicfoodBusin', keyTitle: '公糧業者家數' }),
        new KeyListItem({ key: 'publicfoodStock', keyTitle: '公糧存量' }),
        new KeyListItem({ key: 'rollingFacility', keyTitle: '礱碾設施' }),
        new KeyListItem({ key: 'safetyStock', keyTitle: '公糧安全存量' }),
        new KeyListItem({ key: 'safetyDays', keyTitle: '公糧安全存量天數' }),
        new KeyListItem({ key: 'population', keyTitle: '縣市人口數' }),
        new KeyListItem({ key: 'availableDays', keyTitle: '可供應天數' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '縣市別',
      accessor: 'city',
    },
    {
      Header: '公糧業者家數',
      accessor: 'publicfoodBusin',
    },
    {
      Header: '公糧存量',
      accessor: 'publicfoodStock',
    },
    {
      Header: '可供應天數',
      accessor: 'availableDays',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '縣市別',
      englishField: 'city',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '【必填】\n直轄市、縣市別',
    },
    {
      id: 3,
      chineseField: 'y坐標',
      englishField: 'city_y',
      dataType: '物資資訊',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 4,
      chineseField: 'x坐標',
      englishField: 'city_x',
      dataType: '物資資訊',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 5,
      chineseField: '公糧業者家數',
      englishField: 'publicfood_busin',
      dataType: '物資資訊',
      type: 'int',
      length: '',
      remark: '【必填】',
    },
    {
      id: 6,
      chineseField: '公糧存量',
      englishField: 'publicfood_stock',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark: '【必填】噸',
    },
    {
      id: 7,
      chineseField: '礱碾設施',
      englishField: 'rolling_facility',
      dataType: '物資資訊',
      type: 'int',
      length: '',
      remark: '【必填】架',
    },
    {
      id: 8,
      chineseField: '公糧安全存量',
      englishField: 'safety_stock',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark:
        '【系統判斷】\n依各年度法定值由系統內部修訂公糧安全存量',
    },
    {
      id: 9,
      chineseField: '公糧安全存量天數',
      englishField: 'safety_days',
      dataType: '物資資訊',
      type: 'int',
      length: '',
      remark:
        '【系統判斷】\n依各年度法定值由系統內部修訂公糧安全存量天數',
    },
    {
      id: 10,
      chineseField: '縣市人口數',
      englishField: 'population',
      dataType: '物資資訊',
      type: 'int',
      length: '',
      remark:
        '【系統判斷】\n依「縣市別」「內政部人口統計資料」填入',
    },
    {
      id: 11,
      chineseField: '可供應天數',
      englishField: 'available_days',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark:
        '【系統判斷】\n國人每日食米消費量近10年平均為0.123公斤\n依「公糧存量」/「縣市人口數」/「0.000123」分析「可供應天數」',
    },
    {
      id: 12,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 13,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 14,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 15,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 16,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 17,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 18,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 19,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 20,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 21,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frFoodConfig;
