import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frTelecomBusinessConfig = new BraidingItem({
  id: 31,
  code: '023',
  name: '電信事業',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '交通動員方案',
  mobilizationPlanId: 2,
  mobilizationClassification: '通信',
  mobilizationClassificationId: 19,
  firstLevelAgency: '通傳會',
  firstLevelAgencyId: '',
  secondaryAgency: '',
  secondaryAgencyId: '',

  searchKey: 'companyName',

  fetchDetailData: (id) =>
    ApiService.frTelecomBusiness.readFrTelecomBusinessById(id),
  fetchCategoryData:
    ApiService.frTelecomBusiness.readFrTelecomBusinessPagination,
  queryCategoryData:
    ApiService.frTelecomBusiness.readFrTelecomBusinessQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '代表(所有)人',
      keyList: [
        new KeyListItem({ key: 'companyName', keyTitle: '公司名稱' }),
        new KeyListItem({ key: 'companyAddress', keyTitle: '公司地址' }),
        new KeyListItem({ key: 'companyCity', keyTitle: '公司縣市別' }),
        new KeyListItem({ key: 'companyTown', keyTitle: '公司鄉鎮市區別' }),
        new KeyListItem({ key: 'companyVillage', keyTitle: '公司村里別' }),
        new KeyListItem({ key: 'name', keyTitle: '所有人姓名' }),
        new KeyListItem({ key: 'tel', keyTitle: '所有人聯絡電話' }),
        new KeyListItem({ key: 'contractorName', keyTitle: '承辦人姓名' }),
        new KeyListItem({ key: 'contractorTel', keyTitle: '承辦人聯絡電話' }),
        new KeyListItem({ key: 'agentName', keyTitle: '代理人姓名' }),
        new KeyListItem({ key: 'agentTel', keyTitle: '代理人聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '物資項量',
      keyList: [
        new KeyListItem({ key: 'telecomType', keyTitle: '電信事業別' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '公司名稱',
      accessor: 'companyName',
    },
    {
      Header: '公司地址',
      accessor: 'companyAddress',
    },
    {
      Header: '電信事業別',
      accessor: 'telecomType',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '公司名稱',
      englishField: 'company_name',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】',
    },
    {
      id: 3,
      chineseField: '公司地址',
      englishField: 'company_address',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 4,
      chineseField: '公司縣市別',
      englishField: 'company_city',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 5,
      chineseField: '公司鄉鎮市區別',
      englishField: 'company_town',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 6,
      chineseField: '公司村里別',
      englishField: 'company_village',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 7,
      chineseField: '公司y坐標',
      englishField: 'company_y',
      dataType: '代表(所有)人',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 8,
      chineseField: '公司x坐標',
      englishField: 'company_x',
      dataType: '代表(所有)人',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 9,
      chineseField: '所有人姓名',
      englishField: 'name',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 10,
      chineseField: '所有人聯絡電話',
      englishField: 'tel',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 30,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 11,
      chineseField: '承辦人姓名',
      englishField: 'contractor_name',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 12,
      chineseField: '承辦人聯絡電話',
      englishField: 'contractor_tel',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 100,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 13,
      chineseField: '代理人姓名',
      englishField: 'agent_name',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 14,
      chineseField: '代理人聯絡電話',
      englishField: 'agent_tel',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 100,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 15,
      chineseField: '業別',
      englishField: 'telecom_type',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】請參據「114年通信動員準備計畫」附錄五"業別"欄位填入',
    },
    {
      id: 16,
      chineseField: '電臺名稱',
      englishField: 'radio_name',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 200,
      remark: '提供廣電及衛星事業填註電臺資訊',
    },
    {
      id: 17,
      chineseField: '電臺地址',
      englishField: 'radio_address',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 200,
      remark: '提供廣電及衛星事業填註電臺資訊',
    },
    {
      id: 18,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 19,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 20,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 21,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 22,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 23,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 24,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 25,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 26,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 27,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frTelecomBusinessConfig;
