import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frVehicletransportConfig = new BraidingItem({
  id: 16,
  code: '010',
  name: '車輛輸具',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '交通動員方案',
  mobilizationPlanId: 2,
  mobilizationClassification: '車輛(車輛)',
  mobilizationClassificationId: 11,
  firstLevelAgency: '交通部',
  firstLevelAgencyId: '',
  secondaryAgency: '公路局',
  secondaryAgencyId: '',

  searchKey: 'companyName',

  fetchDetailData: (id) =>
    ApiService.frVehicletransport.readFrVehicletransportById(id),
  fetchCategoryData:
    ApiService.frVehicletransport.readFrVehicletransportPagination,
  queryCategoryData:
    ApiService.frVehicletransport.readFrVehicletransportQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '代表(所有)人',
      keyList: [
        new KeyListItem({ key: 'name', keyTitle: '車主姓名' }),
        new KeyListItem({ key: 'birthdate', keyTitle: '出生年月日' }),
        new KeyListItem({ key: 'age', keyTitle: '年齡' }),
        new KeyListItem({ key: 'pid', keyTitle: '身分證字號(統一編號)' }),
        new KeyListItem({ key: 'gender', keyTitle: '性別' }),
        new KeyListItem({ key: 'car_address', keyTitle: '車籍地址' }),
        new KeyListItem({ key: 'habitation', keyTitle: '戶籍地' }),
        new KeyListItem({ key: 'abodeCity', keyTitle: '居住縣市別' }),
        new KeyListItem({ key: 'abodeTown', keyTitle: '居住鄉鎮市區別' }),
        new KeyListItem({ key: 'abodeVillage', keyTitle: '居住村里別' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '所有單位',
      keyList: [
        new KeyListItem({ key: 'tel', keyTitle: '聯絡電話' }),
        new KeyListItem({ key: 'manageUnit', keyTitle: '編管單位' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '機具資訊',
      keyList: [
        new KeyListItem({ key: 'cartype', keyTitle: '車輛類別' }),
        new KeyListItem({ key: 'carweight', keyTitle: '車輛重量' }),
        new KeyListItem({ key: 'makedate', keyTitle: '出廠年份' }),
        new KeyListItem({ key: 'checkdate', keyTitle: '定檢日期' }),
        new KeyListItem({ key: 'yearlycheckstatus', keyTitle: '年度定檢情形' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '徵購徵用',
      keyList: [
        new KeyListItem({ key: 'deputyid', keyTitle: '身分證字號' }),
        new KeyListItem({ key: 'levyType', keyTitle: '徵用類別' }),
        new KeyListItem({ key: 'levyUnit', keyTitle: '徵用機關' }),
        new KeyListItem({ key: 'levyPlace', keyTitle: '徵用地點' }),
        new KeyListItem({ key: 'levyCity', keyTitle: '徵用縣市別' }),
        new KeyListItem({ key: 'levyTown', keyTitle: '徵用鄉鎮市區別' }),
        new KeyListItem({ key: 'levyVillage', keyTitle: '徵用村里別' }),
        new KeyListItem({ key: 'levyTime', keyTitle: '徵用時間' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '徵用機關',
      accessor: 'levyUnit',
    },
    {
      Header: '徵用地點',
      accessor: 'levyPlace',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '車主姓名',
      englishField: 'name',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark:
        '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 3,
      chineseField: '出生年月日',
      englishField: 'birthdate',
      dataType: '代表(所有)人',
      type: 'datetime',
      length: '',
      remark: '民國年7碼',
    },
    {
      id: 4,
      chineseField: '性別',
      englishField: 'gender',
      dataType: '代表(所有)人',
      type: 'int',
      length: '',
      remark: '性別判斷依身分證第二碼判斷：1、8為男性、2、9為女性',
    },
    {
      id: 5,
      chineseField: '身分證字號(統一編號)',
      englishField: 'pid',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 20,
      remark:
        '【必填】完整不遮蔽\n1.自然人填入身分證字號\n2.法人填入統一編號',
    },
    {
      id: 6,
      chineseField: '車籍地址',
      englishField: 'car_address',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址\nBI規則:縣市別資料順序1.車籍地址、2.戶籍地',
    },
    {
      id: 7,
      chineseField: '戶籍地',
      englishField: 'habitation',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '由戶政系統依身分證字號自動回饋戶籍地址',
    },
    {
      id: 8,
      chineseField: '聯絡電話',
      englishField: 'tel',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 30,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 9,
      chineseField: '編管單位',
      englishField: 'manage_unit',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】\n部會依「監理機關層級對照表」填入',
    },
    {
      id: 10,
      chineseField: '車輛類別',
      englishField: 'cartype',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】依吉普車、小貨車廂式...等17項類別填入',
    },
    {
      id: 11,
      chineseField: '車輛重量',
      englishField: 'carweight',
      dataType: '機具資訊',
      type: 'decimal',
      length: '18,6',
      remark: '重量單位為公斤',
    },
    {
      id: 12,
      chineseField: '出廠年份',
      englishField: 'makedate',
      dataType: '機具資訊',
      type: 'datetime',
      length: '',
      remark: '西元年月6碼',
    },
    {
      id: 13,
      chineseField: '定檢日期',
      englishField: 'checkdate',
      dataType: '機具資訊',
      type: 'datetime',
      length: '',
      remark: '1.西元年月6碼\n2.填註最近一次定檢情形',
    },
    {
      id: 14,
      chineseField: '年度定檢情形',
      englishField: 'yearlycheckstatus',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 50,
      remark: '1.填註合格或不合格\n2.填註最近一次定檢情形',
    },
    {
      id: 15,
      chineseField: '車牌號碼',
      englishField: 'license_plate',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】無中文字',
    },
    {
      id: '【以下資料由後備指揮部另檔提供】',
      chineseField: '',
      englishField: '',
      dataType: '',
      type: '',
      length: '',
      remark: '',
    },
    {
      id: 16,
      chineseField: '身分證字號/統一編號',
      englishField: 'deputypid',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 20,
      remark:
        '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽',
    },
    {
      id: 17,
      chineseField: '徵用類別',
      englishField: 'levy_type',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 18,
      chineseField: '徵用機關',
      englishField: 'levy_unit',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 19,
      chineseField: '徵用地點',
      englishField: 'levy_place',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 20,
      chineseField: '徵用縣市別',
      englishField: 'levy_city',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 21,
      chineseField: '徵用鄉鎮市區別',
      englishField: 'levy_town',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 22,
      chineseField: '徵用村里別',
      englishField: 'levy_village',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 23,
      chineseField: '徵用y坐標',
      englishField: 'levy_y',
      dataType: '徵購徵用',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 24,
      chineseField: '徵用x坐標',
      englishField: 'levy_x',
      dataType: '徵購徵用',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 25,
      chineseField: '徵用時間',
      englishField: 'levy_time',
      dataType: '徵購徵用',
      type: 'datetime',
      length: '',
      remark: '民國年7碼',
    },
    {
      id: 26,
      chineseField: '徵用車輛類別',
      englishField: 'levy_cartype',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】依吉普車、小貨車廂式...等17項類別填入',
    },
    {
      id: 27,
      chineseField: '徵用車牌號碼',
      englishField: 'levy_license_plate',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】勾稽比對欄位',
    },
    {
      id: 28,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 29,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 30,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 31,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 32,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 33,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 34,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 35,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 36,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 37,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frVehicletransportConfig;
