const hr_military_medicalman = [
  {
    name: 'ID',
    value: 'Id',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    role: undefined,
    column: 30,
  },
  {
    name: '不合規原因',
    value: 'NonComplianceReason',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    verticalAlign: 'top',
    role: undefined,
    column: 225,
  },
  {
    name: '是否刪除(V)',
    value: 'DeletedAt',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    column: 125,
  },
  {
    name: '姓名',
    value: 'Name',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role: /^(?!.*[0*.]).*$/,
    role3: /^.{0,200}$/,
    error: "'姓名'是必要欄位",
    error2: "'姓名'請勿有遮罩字元",
    error4: "'姓名'超過長度",
  },
  {
    name: '身分證字號',
    value: 'Pid',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role: /^(?!.*[*]).*$/,
    column: 125,
    error: "'身分證字號'是必要欄位",
    error2: "'身分證字號'請勿有遮罩字元",
  },
  {
    name: '單位',
    value: 'Unit',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,50}$/,
    error4: "'單位'超過長度",
  },
  {
    name: '軍種',
    value: 'MilitaryType',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,50}$/,
    error4: "'軍種'超過長度",
  },
  {
    name: '階級',
    value: 'MilitaryClass',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,50}$/,
    error4: "'階級'超過長度",
  },
];
export default hr_military_medicalman;
