const hr_heavymachinerydriverplan = [
  {
    name: 'ID',
    value: 'Id',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    role: undefined,
    column: 30,
  },
  {
    name: '不合規原因',
    value: 'NonComplianceReason',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    verticalAlign: 'top',
    role: undefined,
    column: 225,
  },
  {
    name: '是否刪除(V)',
    value: 'DeletedAt',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    column: 125,
  },
  {
    name: '姓名',
    value: 'Name',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role: /^(?!.*[0*.]).*$/,
    role3: /^.{0,200}$/,
    error: "'姓名'是必要欄位",
    error2: "'姓名'請勿有遮罩字元",
    error4: "'姓名'超過長度",
  },
  {
    name: '身分證字號',
    value: 'Pid',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role: /^(?!.*[*]).*$/,
    column: 125,
    error: "'身分證字號'是必要欄位",
    error2: "'身分證字號'請勿有遮罩字元",
  },
  // {
  //   name: '演訓類別',
  //   value: 'PlanType',
  //   color: 'rgb(0,0,0)',
  //   background: 'rgb(255,255,255)',
  //   role3: /^.{0,30}$/,
  //   column: 100,
  //   error4: "'演訓類別'超過長度",
  // },
  // {
  //   name: '演訓時間(起)',
  //   value: 'PlanStart',
  //   color: 'rgb(0,0,0)',
  //   background: 'rgb(255,255,255)',
  //   format: 'YYYY-MM-DD',
  //   role: undefined,
  //   column: 125,
  // },
  // {
  //   name: '演訓時間(迄)',
  //   value: 'PlanEnd',
  //   color: 'rgb(0,0,0)',
  //   background: 'rgb(255,255,255)',
  //   format: 'YYYY-MM-DD',
  //   role: undefined,
  //   column: 125,
  // },
  // {
  //   name: '演訓地點',
  //   value: 'PlanPlace',
  //   color: 'rgb(0,0,0)',
  //   background: 'rgb(255,255,255)',
  //   role3: /^.{0,200}$/,
  //   column: 100,
  //   error4: "'演訓地點'超過長度",
  // },
  // {
  //   name: '演訓縣市別',
  //   value: 'PlanCity',
  //   color: 'rgb(0,0,0)',
  //   background: 'rgb(255,255,255)',
  //   role3: /^.{0,10}$/,
  //   column: 125,
  //   error4: "'演訓縣市別'超過長度",
  // },
  // {
  //   name: '演訓鄉鎮市區別',
  //   value: 'PlanTown',
  //   color: 'rgb(0,0,0)',
  //   background: 'rgb(255,255,255)',
  //   role3: /^.{0,10}$/,
  //   column: 150,
  //   error4: "'演訓鄉鎮市區別'超過長度",
  // },
  // {
  //   name: '演訓村里別',
  //   value: 'PlanVillage',
  //   color: 'rgb(0,0,0)',
  //   background: 'rgb(255,255,255)',
  //   role3: /^.{0,10}$/,
  //   column: 125,
  //   error4: "'演訓村里別'超過長度",
  // },
  {
    name: '徵用機關',
    value: 'LevyUnit',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,50}$/,
    column: 100,
    error: "'徵用機關'是必要欄位",
    error4: "'徵用機關'超過長度",
  },
  {
    name: '徵用專長',
    value: 'LevySkill',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,1000}$/,
    column: 100,
    error: "'徵用專長'是必要欄位",
    error4: "'徵用專長'超過長度",
  },
];

export default hr_heavymachinerydriverplan;
