import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frReservoirConfig = new BraidingItem({
  id: 41,
  code: '033',
  name: '水庫設施',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '物資經濟動員方案',
  mobilizationPlanId: 3,
  mobilizationClassification: '水庫',
  mobilizationClassificationId: 27,
  firstLevelAgency: '經濟部',
  firstLevelAgencyId: '',
  secondaryAgency: '水利署',
  secondaryAgencyId: '',

  searchKey: 'reservoirName',

  fetchDetailData: (id) => ApiService.frReservoir.readFrReservoirById(id),
  fetchCategoryData: ApiService.frReservoir.readFrReservoirPagination,
  queryCategoryData: ApiService.frReservoir.readFrReservoirQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '所有單位(管理機關)',
      keyList: [
        new KeyListItem({ key: 'unitName', keyTitle: '名稱' }),
        new KeyListItem({ key: 'unitAddress', keyTitle: '地址' }),
        new KeyListItem({ key: 'unitTel', keyTitle: '聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '物資資訊',
      keyList: [
        new KeyListItem({ key: 'reservoirName', keyTitle: '水庫名稱' }),
        new KeyListItem({ key: 'reservoirX', keyTitle: 'x坐標' }),
        new KeyListItem({ key: 'reservoirY', keyTitle: 'y坐標' }),
        new KeyListItem({ key: 'functiontype', keyTitle: '功能別' }),
        new KeyListItem({ key: 'waterStorage', keyTitle: '有效蓄水量' }),
        new KeyListItem({ key: 'maxStorage', keyTitle: '最大蓄水量' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '水庫名稱',
      accessor: 'reservoirName',
    },
    {
      Header: '有效蓄水量',
      accessor: 'waterStorage',
    },
    {
      Header: '最大蓄水量',
      accessor: 'maxStorage',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '名稱',
      englishField: 'unit_name',
      dataType: '所有單位(管理機關)',
      type: 'nvarchar',
      length: 50,
      remark: '',
    },
    {
      id: 3,
      chineseField: '地址',
      englishField: 'unit_address',
      dataType: '所有單位(管理機關)',
      type: 'nvarchar',
      length: 200,
      remark: '',
    },
    {
      id: 4,
      chineseField: '聯絡電話',
      englishField: 'unit_tel',
      dataType: '所有單位(管理機關)',
      type: 'nvarchar',
      length: 30,
      remark: '',
    },
    {
      id: 5,
      chineseField: '水庫名稱',
      englishField: 'reservoir_name',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 6,
      chineseField: 'y坐標',
      englishField: 'reservoir_y',
      dataType: '物資資訊',
      type: 'decimal',
      length: '9,6',
      remark: '【必填】(wgs-84)',
    },
    {
      id: 7,
      chineseField: 'x坐標',
      englishField: 'reservoir_x',
      dataType: '物資資訊',
      type: 'decimal',
      length: '10,6',
      remark: '【必填】(wgs-84)',
    },
    {
      id: 8,
      chineseField: '功能別',
      englishField: 'functiontype',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】',
    },
    {
      id: 9,
      chineseField: '有效蓄水量',
      englishField: 'water_storage',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark: '【必填】萬噸',
    },
    {
      id: 10,
      chineseField: '最大蓄水量',
      englishField: 'max_storage',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark:
        '【必填】萬噸\n【BI】儀表板-動員圖示：依「有效蓄水量」/「最大蓄水量」分析「蓄水率」',
    },
    {
      id: 11,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 12,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 13,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 14,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 15,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 16,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 17,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 18,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 19,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 20,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frReservoirConfig;
