import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frMajorindustryConfig = new BraidingItem({
  id: 37,
  code: '029',
  name: '重要民生及工業物資',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '物資經濟動員方案',
  mobilizationPlanId: 3,
  mobilizationClassification: '重要工業',
  mobilizationClassificationId: 23,
  firstLevelAgency: '經濟部',
  firstLevelAgencyId: '',
  secondaryAgency: '產發署',
  secondaryAgencyId: '',

  searchKey: 'companyName',

  fetchDetailData: (id) => ApiService.frMajorindustry.readFrMajorindustryById(id),
  fetchCategoryData: ApiService.frMajorindustry.readFrMajorindustryPagination,
  queryCategoryData: ApiService.frMajorindustry.readFrMajorindustryQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '代表(所有)人',
      keyList: [
        new KeyListItem({ key: 'name', keyTitle: '姓名' }),
        new KeyListItem({ key: 'tel', keyTitle: '聯絡電話' }),
        new KeyListItem({ key: 'deputyname', keyTitle: '代理人' }),
        new KeyListItem({ key: 'deputytel', keyTitle: '代理人電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '所有單位',
      keyList: [
        new KeyListItem({ key: 'companyName', keyTitle: '公司名稱' }),
        new KeyListItem({ key: 'companyAddress', keyTitle: '公司地址' }),
        new KeyListItem({ key: 'companyCity', keyTitle: '公司縣市別' }),
        new KeyListItem({ key: 'companyTown', keyTitle: '公司鄉鎮市區別' }),
        new KeyListItem({ key: 'companyVillage', keyTitle: '公司村里別' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '工廠(固定設施)資訊',
      keyList: [
        new KeyListItem({ key: 'factoryStatus', keyTitle: '工廠現況' }),
        new KeyListItem({ key: 'factoryAddress', keyTitle: '工廠所在地' }),
        new KeyListItem({ key: 'factoryCity', keyTitle: '工廠縣市別' }),
        new KeyListItem({ key: 'factoryTown', keyTitle: '工廠鄉鎮市區別' }),
        new KeyListItem({ key: 'factoryVillage', keyTitle: '工廠村里別' }),
        new KeyListItem({ key: 'factoryType', keyTitle: '產業類別' }),
        new KeyListItem({ key: 'productName', keyTitle: '產品名稱' }),
        new KeyListItem({ key: 'factoryNo', keyTitle: '工廠號碼' }),
        new KeyListItem({ key: 'factoryUniteno', keyTitle: '統一編號' }),
        new KeyListItem({ key: 'factoryTel', keyTitle: '工廠聯絡電話' }),
        new KeyListItem({ key: 'factoryKind', keyTitle: '產業別' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '軍需簽證',
      keyList: [
        new KeyListItem({ key: 'militaryType', keyTitle: '軍需類別' }),
        new KeyListItem({ key: 'militaryUnit', keyTitle: '軍需單位' }),
        new KeyListItem({ key: 'factoryName', keyTitle: '動員工廠名稱' }),
        new KeyListItem({ key: 'militaryUniteno', keyTitle: '統一編號' }),
        new KeyListItem({ key: 'produceSystem', keyTitle: '生產體系' }),
        new KeyListItem({ key: 'produceProject', keyTitle: '生產項目' }),
        new KeyListItem({ key: 'materialName', keyTitle: '材料元件名稱' }),
        new KeyListItem({ key: 'model', keyTitle: '規格' }),
        new KeyListItem({ key: 'unit', keyTitle: '單位' }),
        new KeyListItem({ key: 'quantity', keyTitle: '數量' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '公司名稱',
      accessor: 'companyName',
    },
    {
      Header: '公司地址',
      accessor: 'companyAddress',
    },
    {
      Header: '工廠現況',
      accessor: 'factoryStatus',
    },
    {
      Header: '工廠所在地',
      accessor: 'factoryAddress',
    },
    {
      Header: '產業類別',
      accessor: 'factoryType',
    },
    {
      Header: '產品名稱',
      accessor: 'productName',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '姓名',
      englishField: 'name',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 3,
      chineseField: '聯絡電話',
      englishField: 'tel',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 30,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 4,
      chineseField: '代理人',
      englishField: 'deputyname',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 5,
      chineseField: '代理人電話',
      englishField: 'deputytel',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 30,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 6,
      chineseField: '公司名稱',
      englishField: 'company_name',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 7,
      chineseField: '公司地址',
      englishField: 'company_address',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】',
    },
    {
      id: 8,
      chineseField: '公司縣市別',
      englishField: 'company_city',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 9,
      chineseField: '公司鄉鎮市區別',
      englishField: 'company_town',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 10,
      chineseField: '公司村里別',
      englishField: 'company_village',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 11,
      chineseField: '公司y坐標',
      englishField: 'company_y',
      dataType: '所有單位',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 12,
      chineseField: '公司x坐標',
      englishField: 'company_x',
      dataType: '所有單位',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 13,
      chineseField: '統一編號',
      englishField: 'factory_uniteno',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】',
    },
    {
      id: 14,
      chineseField: '工廠現況',
      englishField: 'factory_status',
      dataType: '工廠(固定設施)資訊',
      type: 'nvarchar',
      length: 10,
      remark: '依工廠公示資料填入\n生產中、停工、歇業、設立許可逾\n期失效、設立許可註銷等資訊',
    },
    {
      id: 15,
      chineseField: '工廠所在地',
      englishField: 'factory_address',
      dataType: '工廠(固定設施)資訊',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】',
    },
    {
      id: 16,
      chineseField: '工廠縣市別',
      englishField: 'factory_city',
      dataType: '工廠(固定設施)資訊',
      type: 'nvarchar',
      length: 10,
      remark: '【BI縣市別欄位】\n直轄市、縣市別',
    },
    {
      id: 17,
      chineseField: '工廠鄉鎮市區別',
      englishField: 'factory_town',
      dataType: '工廠(固定設施)資訊',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 18,
      chineseField: '工廠村里別',
      englishField: 'factory_village',
      dataType: '工廠(固定設施)資訊',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 19,
      chineseField: '工廠y坐標',
      englishField: 'factory_y',
      dataType: '工廠(固定設施)資訊',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 20,
      chineseField: '工廠x坐標',
      englishField: 'factory_x',
      dataType: '工廠(固定設施)資訊',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 21,
      chineseField: '工廠聯絡電話',
      englishField: 'factory_tel',
      dataType: '工廠(固定設施)資訊',
      type: 'nvarchar',
      length: 30,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 22,
      chineseField: '工廠登記編號',
      englishField: 'factory_no',
      dataType: '工廠(固定設施)資訊',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】8碼',
    },
    {
      id: 23,
      chineseField: '產業別',
      englishField: 'factory_kind',
      dataType: '工廠(固定設施)資訊',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】\n對應「年度重要民生及工業物資動員準備計畫」\n家數現況分析統計表之「業別」欄位填入',
    },
    {
      id: 24,
      chineseField: '產業類別',
      englishField: 'factory_type',
      dataType: '工廠(固定設施)資訊',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】\n對應「年度重要民生及工業物資動員準備計畫」\n家數現況分析統計表之「類別」欄位填入',
    },
    {
      id: 25,
      chineseField: '產品名稱',
      englishField: 'product_name',
      dataType: '工廠(固定設施)資訊',
      type: 'nvarchar',
      length: 200,
      remark: '完整描述生產品項',
    },
    {
      id: '【以下資料由後備指揮部另檔提供】',
      chineseField: '',
      englishField: '',
      dataType: '',
      type: '',
      length: '',
      remark: '',
    },
    {
      id: 26,
      chineseField: '軍需類別',
      englishField: 'military_type',
      dataType: '軍需簽證',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】\n對應「年度重要民生及工業物資動員準備計畫」\n家數現況分析統計表之「類別」欄位填入\n勾稽比對欄位',
    },
    {
      id: 27,
      chineseField: '軍需單位',
      englishField: 'military_unit',
      dataType: '軍需簽證',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 28,
      chineseField: '動員工廠名稱',
      englishField: 'factory_name',
      dataType: '軍需簽證',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 29,
      chineseField: '軍需統一編號',
      englishField: 'military_uniteno',
      dataType: '軍需簽證',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】勾稽比對欄位',
    },
    {
      id: 30,
      chineseField: '生產體系',
      englishField: 'produce_system',
      dataType: '軍需簽證',
      type: 'nvarchar',
      length: 100,
      remark: '【必填】',
    },
    {
      id: 31,
      chineseField: '生產項目',
      englishField: 'produce_project',
      dataType: '軍需簽證',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 32,
      chineseField: '材料元件名稱',
      englishField: 'material_name',
      dataType: '軍需簽證',
      type: 'nvarchar',
      length: 50,
      remark: '',
    },
    {
      id: 33,
      chineseField: '規格',
      englishField: 'model',
      dataType: '軍需簽證',
      type: 'nvarchar',
      length: 50,
      remark: '',
    },
    {
      id: 34,
      chineseField: '單位',
      englishField: 'unit',
      dataType: '軍需簽證',
      type: 'nvarchar',
      length: 10,
      remark: '',
    },
    {
      id: 35,
      chineseField: '數量',
      englishField: 'quantity',
      dataType: '軍需簽證',
      type: 'decimal',
      length: '18,6',
      remark: '',
    },
    {
      id: 36,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 37,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 38,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 39,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 40,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 41,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 42,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 43,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 44,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 45,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frMajorindustryConfig;
