const fr_radiation_protectplan = [
  {
    name: 'ID',
    value: 'Id',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    role: undefined,
    column: 30,
  },
  {
    name: '不合規原因',
    value: 'NonComplianceReason',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    verticalAlign: 'top',
    role: undefined,
    column: 225,
  },
  {
    name: '是否刪除(V)',
    value: 'DeletedAt',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    column: 125,
  },
  {
    name: '演訓公司名稱',
    value: 'CompanyName',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,30}$/,
    column: 150,
    error: "'演訓公司名稱'是必要欄位",
    error4: "'演訓公司名稱'超過長度",
  },
  {
    name: '演訓防護能量名稱',
    value: 'ProtectionName',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,100}$/,
    column: 200,
    error: "'演訓防護能量名稱'是必要欄位",
    error4: "'演訓防護能量名稱'超過長度",
  },
  {
    name: '演訓數量',
    value: 'Quality',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role: undefined,
    column: 100,
    error: "'演訓數量'是必要欄位",
  },
  {
    name: '演訓類別',
    value: 'PlanType',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,30}$/,
    column: 100,
    error: "'演訓類別'是必要欄位",
    error4: "'演訓類別'超過長度",
  },
  {
    name: '演訓時間(起)',
    value: 'PlanStart',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    format: 'YYYY-MM-DD',
    role: undefined,
    column: 125,
    error: "'演訓時間(起)'是必要欄位",
  },
  {
    name: '演訓時間(迄)',
    value: 'PlanEnd',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    format: 'YYYY-MM-DD',
    role: undefined,
    column: 125,
    error: "'演訓時間(迄)'是必要欄位",
  },
  {
    name: '演訓地點',
    value: 'PlanPlace',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,200}$/,
    column: 100,
    error: "'演訓地點'是必要欄位",
    error4: "'演訓地點'超過長度",
  },
  {
    name: '演訓縣市別',
    value: 'PlanCity',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,10}$/,
    column: 125,
    error4: "'演訓縣市別'超過長度",
  },
  {
    name: '演訓鄉鎮市區別',
    value: 'PlanTown',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,10}$/,
    column: 150,
    error4: "'演訓鄉鎮市區別'超過長度",
  },
  {
    name: '演訓村里別',
    value: 'PlanVillage',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,10}$/,
    column: 125,
    error4: "'演訓村里別'超過長度",
  },
];

export default fr_radiation_protectplan;
