const fr_veteranshomes = [
  {
    name: 'ID',
    value: 'Id',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    role: undefined,
    column: 30,
  },
  {
    name: '不合規原因',
    value: 'NonComplianceReason',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    verticalAlign: 'top',
    role: undefined,
    column: 225,
  },
  {
    name: '是否刪除(V)',
    value: 'DeletedAt',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    column: 125,
  },
  {
    name: '姓名',
    value: 'Name',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role: /^(?!.*[0*.]).*$/,
    role3: /^.{0,200}$/,
    error: "'姓名'是必要欄位",
    error2: "'姓名'請勿有遮罩字元",
    error4: "'姓名'超過長度",
  },
  {
    name: '職稱',
    value: 'Title',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,30}$/,
    error4: "'職稱'超過長度",
  },
  {
    name: '聯絡電話',
    value: 'Tel',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,30}$/,
    column: 110,
    error4: "'聯絡電話'超過長度",
  },
  {
    name: '機構名稱',
    value: 'OrgName',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,50}$/,
    column: 100,
    error: "'機構名稱'是必要欄位",
    error4: "'機構名稱'超過長度",
  },
  {
    name: '機構地址',
    value: 'OrgAddress',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,200}$/,
    column: 100,
    error: "'機構地址'是必要欄位",
    error4: "'機構地址'超過長度",
  },
  {
    name: '機構縣市別',
    value: 'OrgCity',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,10}$/,
    column: 125,
    error4: "'機構縣市別'超過長度",
  },
  {
    name: '機構鄉鎮市區別',
    value: 'OrgTown',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,10}$/,
    column: 150,
    error4: "'機構鄉鎮市區別'超過長度",
  },
  {
    name: '機構村里別',
    value: 'OrgVillage',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,10}$/,
    column: 125,
    error4: "'機構村里別'超過長度",
  },
  {
    name: '機構聯絡電話',
    value: 'OrgTel',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,30}$/,
    column: 150,
    error4: "'機構聯絡電話'超過長度",
  },
  {
    name: '平時規定床位',
    value: 'RegBedNo',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role5: /^\d+$/,
    column: 150,
    error: "'平時規定床位'是必要欄位",
    error5: "'平時規定床位'格式錯誤",
  },
  {
    name: '平時安置人數',
    value: 'RegOccNo',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role5: /^\d+$/,
    column: 150,
    error: "'平時安置人數'是必要欄位",
    error5: "'平時安置人數'格式錯誤",
  },
  {
    name: '戰時整備床位',
    value: 'WartmagBedNo',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role5: /^\d+$/,
    column: 150,
    error: "'戰時管用床位'是必要欄位",
    error5: "'戰時整備床位'格式錯誤",
  },
  {
    name: '戰時安置人數',
    value: 'WartmagOccNo',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role5: /^\d+$/,
    column: 150,
    error: "'戰時安置人數'是必要欄位",
    error5: "'戰時安置人數'格式錯誤",
  },
];

export default fr_veteranshomes;
