const fr_vehicletransport = [
  {
    name: 'ID',
    value: 'Id',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    role: undefined,
    column: 30,
  },
  {
    name: '不合規原因',
    value: 'NonComplianceReason',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    verticalAlign: 'top',
    role: undefined,
    column: 225,
  },
  {
    name: '是否刪除(V)',
    value: 'DeletedAt',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    column: 125,
  },
  {
    name: '車主姓名',
    value: 'Name',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role: /^(?!.*[0*.]).*$/,
    role3: /^.{0,200}$/,
    column: 125,
    error: "'車主姓名'是必要欄位",
    error2: "'車主姓名'請勿有遮罩字元",
    error4: "'車主姓名'超過長度",
  },
  {
    name: '出生年月日',
    value: 'Birthdate',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    format: 'YYYY-MM-DD',
    role: undefined,
    column: 125,
  },
  {
    name: '身分證字號(統一編號)',
    value: 'Pid',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role: /^(?!.*[*]).*$/,
    column: 200,
    error: "'身分證字號(統一編號)'是必要欄位",
    error2: "'身分證字號(統一編號)'請勿有遮罩字元",
  },
  {
    name: '車籍地址',
    value: 'CarAddress',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,200}$/,
    column: 100,
    error: "'車籍地址'是必要欄位",
    error4: "'車籍地址'超過長度",
  },
  {
    name: '戶籍地',
    value: 'habitation',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,200}$/,
    column: 125,
    error4: "'戶籍地'超過長度",
  },
  // {
  //   name: '居住縣市別',
  //   value: 'AbodeCity',
  //   color: 'rgb(0,0,0)',
  //   background: 'rgb(255,255,255)',
  //   role3: /^.{0,10}$/,
  //   column: 125,
  //   error4: "'居住縣市別'超過長度",
  // },
  // {
  //   name: '居住鄉鎮市區別',
  //   value: 'AbodeTown',
  //   color: 'rgb(0,0,0)',
  //   background: 'rgb(255,255,255)',
  //   role3: /^.{0,10}$/,
  //   column: 150,
  //   error4: "'居住鄉鎮市區別'超過長度",
  // },
  // {
  //   name: '居住村里別',
  //   value: 'AbodeVillage',
  //   color: 'rgb(0,0,0)',
  //   background: 'rgb(255,255,255)',
  //   role3: /^.{0,10}$/,
  //   column: 125,
  //   error4: "'居住村里別'超過長度",
  // },
  {
    name: '聯絡電話',
    value: 'Tel',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,30}$/,
    column: 110,
    error4: "'聯絡電話'超過長度",
  },
  {
    name: '編管單位',
    value: 'ManageUnit',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,30}$/,
    column: 100,
    error: "'編管單位'是必要欄位",
    error4: "'編管單位'超過長度",
  },
  {
    name: '車輛類別',
    value: 'Cartype',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,30}$/,
    column: 100,
    error: "'車輛類別'是必要欄位",
    error4: "'車輛類別'超過長度",
  },
  {
    name: '車輛重量',
    value: 'Carweight',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role4: /^\d{0,18}(\.\d{0,6})?$/,
    column: 100,
    error4: "'車輛重量'格式錯誤",
  },
  {
    name: '出廠年份',
    value: 'Makedate',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role5: /^\d{6}$/,
    column: 100,
    error5: "'出廠年份'格式錯誤",
  },
  {
    name: '定檢日期',
    value: 'Checkdate',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role5: /^\d{6}$/,
    column: 100,
    error5: "'定檢日期'格式錯誤",
  },
  {
    name: '年度定檢情形',
    value: 'Yearlycheckstatus',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,50}$/,
    column: 150,
    error4: "'年度定檢情形'超過長度",
  },
  {
    name: '車牌號碼',
    value: 'LicensePlate',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,50}$/,
    column: 100,
    error: "'車牌號碼'是必要欄位",
    error4: "'車牌號碼'超過長度",
  },
];

export default fr_vehicletransport;
