const fr_water_purify = [
  {
    name: 'ID',
    value: 'Id',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    role: undefined,
    column: 30,
  },
  {
    name: '不合規原因',
    value: 'NonComplianceReason',
    color: 'rgb(0,0,0)',
    background: 'rgb(200,200,200)',
    verticalAlign: 'top',
    role: undefined,
    column: 225,
  },
  {
    name: '是否刪除(V)',
    value: 'DeletedAt',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    column: 125,
  },
  {
    name: '名稱',
    value: 'UnitName',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,50}$/,
    error: "'名稱'是必要欄位",
    error4: "'名稱'超過長度",
  },
  {
    name: '地址',
    value: 'UnitAddress',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,200}$/,
    error4: "'地址'超過長度",
  },
  {
    name: '聯絡電話',
    value: 'UnitTel',
    color: 'rgb(0,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,30}$/,
    column: 110,
    error4: "'聯絡電話'超過長度",
  },
  {
    name: '供水系統',
    value: 'WaterSystem',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,50}$/,
    column: 100,
    error: "'供水系統'是必要欄位",
    error4: "'供水系統'超過長度",
  },
  {
    name: '淨水設施名稱',
    value: 'FacilityName',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role3: /^.{0,50}$/,
    column: 150,
    error: "'淨水設施名稱'是必要欄位",
    error4: "'淨水設施名稱'超過長度",
  },
  {
    name: 'y坐標',
    value: 'FacilityY',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role4: /^\d{0,9}(\.\d{0,6})?$/,
    error: "'y坐標'是必要欄位",
    error4: "'y坐標'格式錯誤",
  },
  {
    name: 'x坐標',
    value: 'FacilityX',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role4: /^\d{0,10}(\.\d{0,6})?$/,
    error: "'x坐標'是必要欄位",
    error4: "'x坐標'格式錯誤",
  },
  {
    name: '每日供水能力',
    value: 'DailyWatersupply',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role4: /^\d{0,18}(\.\d{0,6})?$/,
    column: 150,
    error: "'每日供水能力'是必要欄位",
    error4: "'每日供水能力'格式錯誤",
  },
  {
    name: '供水人口',
    value: 'WaterPopulation',
    color: 'rgb(255,0,0)',
    background: 'rgb(255,255,255)',
    role5: /^\d+$/,
    column: 100,
    error: "'供水人口'是必要欄位",
    error5: "'供水人口'格式錯誤",
  },
];

export default fr_water_purify;
