import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frBackupWellConfig = new BraidingItem({
  id: 43,
  code: '035',
  name: '備援水井',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '物資經濟動員方案',
  mobilizationPlanId: 3,
  mobilizationClassification: '給水',
  mobilizationClassificationId: 28,
  firstLevelAgency: '經濟部',
  firstLevelAgencyId: '',
  secondaryAgency: '水利署',
  secondaryAgencyId: '',

  searchKey: 'backupwellName',

  fetchDetailData: (id) => ApiService.frBackupWell.readFrBackupWellById(id),
  fetchCategoryData: ApiService.frBackupWell.readFrBackupWellPagination,
  queryCategoryData: ApiService.frBackupWell.readFrBackupWellQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '所有單位(管理機關)',
      keyList: [
        new KeyListItem({ key: 'unitName', keyTitle: '名稱' }),
        new KeyListItem({ key: 'unitAddress', keyTitle: '地址' }),
        new KeyListItem({ key: 'unitTel', keyTitle: '聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '物資資訊',
      keyList: [
        new KeyListItem({ key: 'backupwellName', keyTitle: '備援水井名稱' }),
        new KeyListItem({ key: 'backupwellX', keyTitle: 'x坐標' }),
        new KeyListItem({ key: 'backupwellY', keyTitle: 'y坐標' }),
        new KeyListItem({ key: 'dailyWatersupply', keyTitle: '每日供水能力' }),
        new KeyListItem({ key: 'waterPopulation', keyTitle: '供水人口' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '備援水井名稱',
      accessor: 'backupwellName',
    },
    {
      Header: '每日供水能力',
      accessor: 'dailyWatersupply',
    },
    {
      Header: '供水人口',
      accessor: 'waterPopulation',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '名稱',
      englishField: 'unit_name',
      dataType: '所有單位(管理機關)',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 3,
      chineseField: '地址',
      englishField: 'unit_address',
      dataType: '所有單位(管理機關)',
      type: 'nvarchar',
      length: 200,
      remark: '完整地址',
    },
    {
      id: 4,
      chineseField: '聯絡電話',
      englishField: 'unit_tel',
      dataType: '所有單位(管理機關)',
      type: 'nvarchar',
      length: 30,
      remark: '',
    },
    {
      id: 5,
      chineseField: '備援水井名稱',
      englishField: 'backupwell_name',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 6,
      chineseField: 'y坐標',
      englishField: 'backupwell_y',
      dataType: '物資資訊',
      type: 'decimal',
      length: '9,6',
      remark: '【必填】(wgs-84)',
    },
    {
      id: 7,
      chineseField: 'x坐標',
      englishField: 'backupwell_x',
      dataType: '物資資訊',
      type: 'decimal',
      length: '10,6',
      remark: '【必填】(wgs-84)',
    },
    {
      id: 8,
      chineseField: '每日供水能力',
      englishField: 'daily_watersupply',
      dataType: '物資資訊',
      type: 'decimal',
      length: '18,6',
      remark: '【必填】噸',
    },
    {
      id: 9,
      chineseField: '供水人口',
      englishField: 'water_population',
      dataType: '物資資訊',
      type: 'int',
      length: '',
      remark: '【必填】',
    },
    {
      id: 10,
      chineseField: '水質檢測',
      englishField: 'water_testing',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 10,
      remark: '',
    },
    {
      id: 11,
      chineseField: '使用方式',
      englishField: 'usage',
      dataType: '物資資訊',
      type: 'nvarchar',
      length: 50,
      remark: '',
    },
    {
      id: 12,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 13,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 14,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 15,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 16,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 17,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 18,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 19,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 20,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 21,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frBackupWellConfig;
