import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';
import HrFiremanpowerPlanResponse from '../../../dataModels/HrFiremanpowerPlan/HrFiremanpowerPlanResponse';

const hrFiremanpowerConfig = new BraidingItem({
  id: 4,
  code: '902',
  name: '消防人力(演訓人力)',
  type: '人力',
  typeIndex: '1',
  mobilizationPlan: '人力動員方案',
  mobilizationPlanId: 1,
  mobilizationClassification: '消防人力',
  mobilizationClassificationId: 3,
  firstLevelAgency: '內政部',
  firstLevelAgencyId: '',
  secondaryAgency: '消防署',
  secondaryAgencyId: '',

  fetchDetailData: (id) => ApiService.hrFiremanpower.readHrFiremanpowerById(id),
  fetchCategoryData: ApiService.hrFiremanpower.readHrFiremanpowerPagination,
  queryCategoryData:
    ApiService.hrFiremanpower.readHrFiremanpowerQueryPagination,
  fetchPlanData: ({ pid }) =>
    ApiService.hrFiremanpowerPlan.readHrFiremanpowerPlanByPid(pid),

  planDataModel: HrFiremanpowerPlanResponse,

  fetchUniqueDetailData: (id) =>
    ApiService.hrFiremanpower.readUniqueHrFiremanpowerById(id),
  fetchUniqueCategoryData:
    ApiService.hrFiremanpower.readUniqueHrFiremanpowerPagination,
  queryUniqueCategoryData:
    ApiService.hrFiremanpower.readUniqueHrFiremanpowerQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '基本資料',
      keyList: [
        new KeyListItem({ key: 'name', keyTitle: '姓名' }),
        new KeyListItem({ key: 'birthdate', keyTitle: '出生年月日' }),
        new KeyListItem({ key: 'age', keyTitle: '年齡' }),
        new KeyListItem({ key: 'pid', keyTitle: '身分證字號' }),
        new KeyListItem({ key: 'gender', keyTitle: '性別' }),
        new KeyListItem({ key: 'habitation', keyTitle: '戶籍地' }),
        new KeyListItem({ key: 'habitatCity', keyTitle: '戶籍縣市別' }),
        new KeyListItem({ key: 'habitatTown', keyTitle: '戶籍鄉鎮市區別' }),
        new KeyListItem({ key: 'habitatVillage', keyTitle: '戶籍村里別' }),
        new KeyListItem({ key: 'abode', keyTitle: '居住所' }),
        new KeyListItem({ key: 'abodeCity', keyTitle: '居住縣市別' }),
        new KeyListItem({ key: 'abodeTown', keyTitle: '居住鄉鎮市區別' }),
        new KeyListItem({ key: 'abodeVillage', keyTitle: '居住村里別' }),
        new KeyListItem({ key: 'tel', keyTitle: '聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '編管資料',
      keyList: [
        new KeyListItem({ key: 'manageType', keyTitle: '編管類型' }),
        new KeyListItem({ key: 'manageUnit', keyTitle: '編管機構' }),
        new KeyListItem({ key: 'managePlace', keyTitle: '編管地點' }),
        new KeyListItem({ key: 'manageCity', keyTitle: '編管縣市別' }),
        new KeyListItem({ key: 'manageTown', keyTitle: '編管鄉鎮市區別' }),
        new KeyListItem({ key: 'manageVillage', keyTitle: '編管村里別' }),
        new KeyListItem({ key: 'stationPlace', keyTitle: '駐地地點' }),
        new KeyListItem({ key: 'stationCity', keyTitle: '駐地縣市別' }),
        new KeyListItem({ key: 'stationTown', keyTitle: '駐地鄉鎮市區別' }),
        new KeyListItem({ key: 'stationVillage', keyTitle: '駐地村里別' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '人力資訊',
      keyList: [
        new KeyListItem({ key: 'updatedateString', keyTitle: '異動時間' }),
        new KeyListItem({ key: 'organDist1', keyTitle: '編組區分(一)' }),
        new KeyListItem({ key: 'organDist2', keyTitle: '編組區分(二)' }),
        new KeyListItem({ key: 'organDist3', keyTitle: '編組區分(三)' }),
        new KeyListItem({ key: 'organDist4', keyTitle: '編組區分(四)' }),
        new KeyListItem({ key: 'organTitle', keyTitle: '編組職稱' }),
        new KeyListItem({ key: 'lic', keyTitle: '證照' }),
      ],
    }),
  ],
  planConfigList: [
    new ConfigListItem({
      sectionTitle: '動員演訓(徵用情形)',
      keyList: [
        new KeyListItem({ key: 'planType', keyTitle: '演訓類別' }),
        new KeyListItem({ key: 'planStart', keyTitle: '演訓時間(起)' }),
        new KeyListItem({ key: 'planEnd', keyTitle: '演訓時間(迄)' }),
        new KeyListItem({ key: 'planPlace', keyTitle: '演訓地點' }),
        new KeyListItem({ key: 'planCity', keyTitle: '演訓縣市別' }),
        new KeyListItem({ key: 'planTown', keyTitle: '演訓鄉鎮市區別' }),
        new KeyListItem({ key: 'planVillage', keyTitle: '演訓村里別' }),
      ],
    }),
  ],
  categoryTableHeader: [
    {
      Header: '姓名',
      accessor: 'name',
    },
    {
      Header: '身分證字號',
      accessor: 'pid',
    },
    {
      Header: '編管類型',
      accessor: 'manageType',
    },
    {
      Header: '編管機構',
      accessor: 'manageUnit',
    },
    {
      Header: '編管地點',
      accessor: 'managePlace',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '姓名',
      englishField: 'name',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 200,
      remark:
        '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.依演習類別計次，來源資料姓名具重複性\n4.可輸入英文、羅馬拼音、小數點\n5.原住民特殊符號',
    },
    {
      id: 3,
      chineseField: '身分證字號',
      englishField: 'pid',
      dataType: '基本資料',
      type: 'nvarchar',
      length: 20,
      remark:
        '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.依演習類別計次，來源資料身分證字號具重複性',
    },
    {
      id: 4,
      chineseField: '演訓類別',
      englishField: 'plan_type',
      dataType: '動員演訓(徵用情形)',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】',
    },
    {
      id: 5,
      chineseField: '演訓時間(起)',
      englishField: 'plan_start',
      dataType: '動員演訓(徵用情形)',
      type: 'datetime',
      remark: '【必填】民國年7碼',
    },
    {
      id: 6,
      chineseField: '演訓時間(迄)',
      englishField: 'plan_end',
      dataType: '動員演訓(徵用情形)',
      type: 'datetime',
      remark: '【必填】民國年7碼',
    },
    {
      id: 7,
      chineseField: '演訓地點',
      englishField: 'plan_place',
      dataType: '動員演訓(徵用情形)',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 8,
      chineseField: '演訓縣市別',
      englishField: 'plan_city',
      dataType: '動員演訓(徵用情形)',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 9,
      chineseField: '演訓鄉鎮市區別',
      englishField: 'plan_town',
      dataType: '動員演訓(徵用情形)',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 10,
      chineseField: '演訓村里別',
      englishField: 'plan_village',
      dataType: '動員演訓(徵用情形)',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 11,
      chineseField: '演訓y坐標',
      englishField: 'plan_y',
      dataType: '動員演訓(徵用情形)',
      type: 'decimal',
      length: 9.6,
      remark: '編管機關毋須填寫',
    },
    {
      id: 12,
      chineseField: '演訓x坐標',
      englishField: 'plan_x',
      dataType: '動員演訓(徵用情形)',
      type: 'decimal',
      length: 10.6,
      remark: '編管機關毋須填寫',
    },
    {
      id: 13,
      chineseField: '異動時間',
      englishField: 'updatedate',
      dataType: '人力資訊',
      type: 'datetime',
      length: '',
      remark: '系統判斷',
    },
    {
      id: 14,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 15,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 16,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 17,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 18,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 19,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 20,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 21,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 22,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 23,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default hrFiremanpowerConfig;
