import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frDedicatedTelecomConfig = new BraidingItem({
  id: 30,
  code: '022',
  name: '專用電信',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '交通動員方案',
  mobilizationPlanId: 2,
  mobilizationClassification: '通信',
  mobilizationClassificationId: 19,
  firstLevelAgency: '通傳會',
  firstLevelAgencyId: '',
  secondaryAgency: '',
  secondaryAgencyId: '',

  searchKey: 'setupName',

  fetchDetailData: (id) =>
    ApiService.frDedicatedTelecom.readFrDedicatedTelecomById(id),
  fetchCategoryData:
    ApiService.frDedicatedTelecom.readFrDedicatedTelecomPagination,
  queryCategoryData:
    ApiService.frDedicatedTelecom.readFrDedicatedTelecomQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '代表(所有)人',
      keyList: [
        new KeyListItem({ key: 'name', keyTitle: '姓名' }),
        new KeyListItem({ key: 'birthdate', keyTitle: '出生年月日' }),
        new KeyListItem({ key: 'gender', keyTitle: '性別' }),
        new KeyListItem({ key: 'pid', keyTitle: '身分證字號' }),
        new KeyListItem({ key: 'abode', keyTitle: '居住所' }),
        new KeyListItem({ key: 'abodeCity', keyTitle: '居住縣市別' }),
        new KeyListItem({ key: 'abodeTown', keyTitle: '居住鄉鎮市區別' }),
        new KeyListItem({ key: 'abodeVillage', keyTitle: '居住村里別' }),
        new KeyListItem({ key: 'habitation', keyTitle: '戶籍地' }),
        new KeyListItem({ key: 'habitatCity', keyTitle: '戶籍縣市別' }),
        new KeyListItem({ key: 'habitatTown', keyTitle: '戶籍鄉鎮市區別' }),
        new KeyListItem({ key: 'habitatVillage', keyTitle: '戶籍村里別' }),
        new KeyListItem({ key: 'tel', keyTitle: '聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '所有單位',
      keyList: [
        new KeyListItem({ key: 'setupName', keyTitle: '專用電信設置者' }),
        new KeyListItem({
          key: 'setupAddress',
          keyTitle: '專用電信設置者地址',
        }),
        new KeyListItem({ key: 'setupCity', keyTitle: '設置者縣市別' }),
        new KeyListItem({ key: 'setupTown', keyTitle: '設置者鄉鎮市區別' }),
        new KeyListItem({ key: 'setupVillage', keyTitle: '設置者村里別' }),
        new KeyListItem({ key: 'setupPname', keyTitle: '聯絡人姓名' }),
        new KeyListItem({ key: 'setupPtel', keyTitle: '聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '物資項量',
      keyList: [
        new KeyListItem({ key: 'eqType', keyTitle: '電信器材種類' }),
        new KeyListItem({ key: 'setQuantity', keyTitle: '設置數量' }),
        new KeyListItem({ key: 'levyEnergy', keyTitle: '可動員能量' }),
        new KeyListItem({ key: 'frequency', keyTitle: '固定臺使用頻率' }),
        new KeyListItem({ key: 'power', keyTitle: '功率範圍' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '專用電信設置者',
      accessor: 'setupName',
    },
    {
      Header: '專用電信設置者地址',
      accessor: 'setupAddress',
    },
    {
      Header: '電信器材種類',
      accessor: 'eqType',
    },
    {
      Header: '設置數量',
      accessor: 'setQuantity',
    },
    {
      Header: '可動員能量',
      accessor: 'levyEnergy',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '姓名',
      englishField: 'name',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark:
        '完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 3,
      chineseField: '出生年月日',
      englishField: 'birthdate',
      dataType: '代表(所有)人',
      type: 'datetime',
      length: '',
      remark: '民國年7碼',
    },
    {
      id: 4,
      chineseField: '性別',
      englishField: 'gender',
      dataType: '代表(所有)人',
      type: 'int',
      length: '',
      remark: '性別判斷依身分證第二碼判斷：1、8為男性、2、9為女性',
    },
    {
      id: 5,
      chineseField: '身分證字號',
      englishField: 'pid',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 20,
      remark:
        '完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽',
    },
    {
      id: 6,
      chineseField: '居住所',
      englishField: 'abode',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '完整地址',
    },
    {
      id: 7,
      chineseField: '居住縣市別',
      englishField: 'abode_city',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 8,
      chineseField: '居住鄉鎮市區別',
      englishField: 'abode_town',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 9,
      chineseField: '居住村里別',
      englishField: 'abode_village',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 10,
      chineseField: '居住y坐標',
      englishField: 'abode_y',
      dataType: '代表(所有)人',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 11,
      chineseField: '居住x坐標',
      englishField: 'abode_x',
      dataType: '代表(所有)人',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 12,
      chineseField: '戶籍地',
      englishField: 'habitation',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '完整地址',
    },
    {
      id: 13,
      chineseField: '戶籍縣市別',
      englishField: 'habitat_city',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 14,
      chineseField: '戶籍鄉鎮市區別',
      englishField: 'habitat_town',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 15,
      chineseField: '戶籍村里別',
      englishField: 'habitat_village',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 16,
      chineseField: '戶籍y坐標',
      englishField: 'habitat_y',
      dataType: '代表(所有)人',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 17,
      chineseField: '戶籍x坐標',
      englishField: 'habitat_x',
      dataType: '代表(所有)人',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 18,
      chineseField: '聯絡電話',
      englishField: 'tel',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 30,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 19,
      chineseField: '專用電信器材種類',
      englishField: 'proeq_type',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 30,
      remark: '',
    },
    {
      id: 20,
      chineseField: '專用電信設置者',
      englishField: 'setup_name',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 50,
      remark: '',
    },
    {
      id: 21,
      chineseField: '專用電信設置者地址',
      englishField: 'setup_address',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 22,
      chineseField: '設置者縣市別',
      englishField: 'setup_city',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 23,
      chineseField: '設置者鄉鎮市區別',
      englishField: 'setup_town',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 24,
      chineseField: '設置者村里別',
      englishField: 'setup_village',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 25,
      chineseField: '設置者y坐標',
      englishField: 'setup_y',
      dataType: '所有單位',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 26,
      chineseField: '設置者x坐標',
      englishField: 'setup_x',
      dataType: '所有單位',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 27,
      chineseField: '聯絡人姓名',
      englishField: 'setup_pname',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 100,
      remark: '完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽',
    },
    {
      id: 28,
      chineseField: '聯絡人電話',
      englishField: 'setup_ptel',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 30,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 29,
      chineseField: '電信器材種類',
      englishField: 'eq_type',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】',
    },
    {
      id: 30,
      chineseField: '設置數量',
      englishField: 'set_quantity',
      dataType: '物資項量',
      type: 'int',
      length: '',
      remark: '【必填】阿拉伯數字',
    },
    {
      id: 31,
      chineseField: '可動員能量',
      englishField: 'levy_energy',
      dataType: '物資項量',
      type: 'int',
      length: '',
      remark: '【必填】阿拉伯數字',
    },
    {
      id: 32,
      chineseField: '固定臺使用頻率',
      englishField: 'frequency',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 800,
      remark: '',
    },
    {
      id: 33,
      chineseField: '功率範圍',
      englishField: 'power',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 800,
      remark: '',
    },
    {
      id: 34,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 35,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 36,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 37,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 38,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 39,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 40,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 41,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 42,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 43,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frDedicatedTelecomConfig;
