import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';
import FrRadiationProtectPlanResponse from '../../../dataModels/FrRadiationProtectPlan/FrRadiationProtectPlanResponse';

const frRadiationProtectConfig = new BraidingItem({
  id: 53,
  code: '943',
  name: '輻射防護(演訓物力)',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '科技動員方案',
  mobilizationPlanId: 5,
  mobilizationClassification: '輻射防護',
  mobilizationClassificationId: 42,
  firstLevelAgency: '核安會',
  firstLevelAgencyId: '',
  secondaryAgency: '',
  secondaryAgencyId: '',

  searchKey: 'companyName',

  fetchDetailData: (id) =>
    ApiService.frRadiationProtect.readFrRadiationProtectById(id),
  fetchCategoryData:
    ApiService.frRadiationProtect.readFrRadiationProtectPagination,
  queryCategoryData:
    ApiService.frRadiationProtect.readFrRadiationProtectQueryPagination,
  fetchPlanData: ({ companyName }) =>
    ApiService.frRadiationProtectPlan.readFrRadiationProtectPlanByCompanyName(
      companyName,
    ),

  planDataModel: FrRadiationProtectPlanResponse,

  configList: [
    new ConfigListItem({
      sectionTitle: '基本資料',
      keyList: [
        new KeyListItem({ key: 'name', keyTitle: '姓名' }),
        new KeyListItem({ key: 'email', keyTitle: '電子郵件' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '所有單位',
      keyList: [
        new KeyListItem({ key: 'companyName', keyTitle: '公司名稱' }),
        new KeyListItem({ key: 'companyAddress', keyTitle: '公司地址' }),
        new KeyListItem({ key: 'companyCity', keyTitle: '公司縣市別' }),
        new KeyListItem({ key: 'companyTown', keyTitle: '公司鄉鎮市區別' }),
        new KeyListItem({ key: 'companyVillage', keyTitle: '公司村里別' }),
        new KeyListItem({ key: 'companytel', keyTitle: '公司聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '物資資訊',
      keyList: [
        new KeyListItem({ key: 'protectionName', keyTitle: '防護能量名稱' }),
        new KeyListItem({ key: 'quality', keyTitle: '數量' }),
      ],
    }),
  ],
  planConfigList: [
    new ConfigListItem({
      sectionTitle: '動員演訓(徵用情形)',
      keyList: [
        new KeyListItem({ key: 'planType', keyTitle: '演訓類別' }),
        new KeyListItem({ key: 'planStart', keyTitle: '演訓時間(起)' }),
        new KeyListItem({ key: 'planEnd', keyTitle: '演訓時間(迄)' }),
        new KeyListItem({ key: 'planPlace', keyTitle: '演訓地點' }),
        new KeyListItem({ key: 'planCity', keyTitle: '演訓縣市別' }),
        new KeyListItem({ key: 'planTown', keyTitle: '演訓鄉鎮市區別' }),
        new KeyListItem({ key: 'planVillage', keyTitle: '演訓村里別' }),
      ],
    }),
  ],
  categoryTableHeader: [
    {
      Header: '公司名稱',
      accessor: 'companyName',
    },
    {
      Header: '公司地址',
      accessor: 'companyAddress',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '演訓公司名稱',
      englishField: 'p_company_name',
      dataType: '動員演訓(徵用情形)',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】完整\nBI規則：BI透過本欄位與編管公司名稱進行串接',
    },
    {
      id: 3,
      chineseField: '演訓防護能量名稱',
      englishField: 'p_protection_name',
      dataType: '動員演訓(徵用情形)',
      type: 'nvarchar',
      length: 100,
      remark:
        '【必填】\nBI規則：BI透過本欄位與編管防護能量名稱進行串接',
    },
    {
      id: 4,
      chineseField: '演訓數量',
      englishField: 'p_quality',
      dataType: '動員演訓(徵用情形)',
      type: 'int',
      remark: '【必填】計量，不要單位',
    },
    {
      id: 5,
      chineseField: '演訓類別',
      englishField: 'plan_type',
      dataType: '動員演訓(徵用情形)',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】',
    },
    {
      id: 6,
      chineseField: '演訓時間(起)',
      englishField: 'plan_start',
      dataType: '動員演訓(徵用情形)',
      type: 'datetime',
      remark: '【必填】民國年7碼',
    },
    {
      id: 7,
      chineseField: '演訓時間(迄)',
      englishField: 'plan_end',
      dataType: '動員演訓(徵用情形)',
      type: 'datetime',
      remark: '【必填】民國年7碼',
    },
    {
      id: 8,
      chineseField: '演訓地點',
      englishField: 'plan_place',
      dataType: '動員演訓(徵用情形)',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 9,
      chineseField: '演訓縣市別',
      englishField: 'plan_city',
      dataType: '動員演訓(徵用情形)',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 10,
      chineseField: '演訓鄉鎮市區別',
      englishField: 'plan_town',
      dataType: '動員演訓(徵用情形)',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 11,
      chineseField: '演訓村里別',
      englishField: 'plan_village',
      dataType: '動員演訓(徵用情形)',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 12,
      chineseField: '演訓y坐標',
      englishField: 'plan_y',
      dataType: '動員演訓(徵用情形)',
      type: 'decimal',
      length: 9.6,
      remark: '編管機關毋須填寫',
    },
    {
      id: 13,
      chineseField: '演訓x坐標',
      englishField: 'plan_x',
      dataType: '動員演訓(徵用情形)',
      type: 'decimal',
      length: 10.6,
      remark: '編管機關毋須填寫',
    },
    {
      id: 14,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 15,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 16,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 17,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 18,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 19,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 20,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 21,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 22,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 23,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frRadiationProtectConfig;
