import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frMedicineConfig = new BraidingItem({
  id: 56,
  code: '045',
  name: '藥品醫材',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '衛生動員方案',
  mobilizationPlanId: 8,
  mobilizationClassification: '藥政',
  mobilizationClassificationId: 54,
  firstLevelAgency: '衛福部',
  firstLevelAgencyId: '',
  secondaryAgency: '食藥署',
  secondaryAgencyId: '',

  searchKey: 'hospitalName',

  fetchDetailData: (id) => ApiService.frMedicine.readFrMedicineById(id),
  fetchCategoryData: ApiService.frMedicine.readFrMedicinePagination,
  queryCategoryData: ApiService.frMedicine.readFrMedicineQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '所有單位',
      keyList: [
        new KeyListItem({ key: 'hospitalName', keyTitle: '儲備醫院名稱' }),
        new KeyListItem({ key: 'hospitalAddress', keyTitle: '儲備醫院地址' }),
        new KeyListItem({ key: 'hospitalCity', keyTitle: '儲備醫院縣市別' }),
        new KeyListItem({
          key: 'hospitalTown',
          keyTitle: '儲備醫院鄉鎮市區別',
        }),
        new KeyListItem({ key: 'hospitalVillage', keyTitle: '儲備醫院村里別' }),
        new KeyListItem({ key: 'hospitalLevel', keyTitle: '儲備醫院動員等級' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '物資資訊',
      keyList: [
        new KeyListItem({ key: 'requirementType', keyTitle: '需求類別' }),
        new KeyListItem({ key: 'itemsType', keyTitle: '品項類別' }),
        new KeyListItem({ key: 'items', keyTitle: '品項' }),
        new KeyListItem({ key: 'unit', keyTitle: '計量單位' }),
        new KeyListItem({ key: 'manageQuality', keyTitle: '編管數量' }),
        new KeyListItem({ key: 'informQuality', keyTitle: '通報數量' }),
        new KeyListItem({ key: 'informDate', keyTitle: '通報週期' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '徵購徵用',
      keyList: [
        new KeyListItem({ key: 'levyHospital', keyTitle: '儲備醫院名稱' }),
        new KeyListItem({ key: 'levyType', keyTitle: '徵購類別' }),
        new KeyListItem({ key: 'levyUnit', keyTitle: '徵用機關' }),
        new KeyListItem({ key: 'levyPlace', keyTitle: '徵購地點' }),
        new KeyListItem({ key: 'levyCity', keyTitle: '徵購縣市別' }),
        new KeyListItem({ key: 'levyTown', keyTitle: '徵購鄉鎮市區別' }),
        new KeyListItem({ key: 'levyVillage', keyTitle: '徵購村里別' }),
        new KeyListItem({ key: 'levyDate', keyTitle: '徵購時間' }),
        new KeyListItem({ key: 'visitems', keyTitle: '簽證品項' }),
        new KeyListItem({ key: 'visaquantity', keyTitle: '簽證數量' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '儲備醫院名稱',
      accessor: 'hospitalName',
    },
    {
      Header: '儲備醫院地址',
      accessor: 'hospitalAddress',
    },
    {
      Header: '品項類別',
      accessor: 'itemsType',
    },
    {
      Header: '品項',
      accessor: 'items',
    },
    {
      Header: '徵用機關',
      accessor: 'levyUnit',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '儲備醫院名稱',
      englishField: 'hospital_name',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 3,
      chineseField: '儲備醫院地址',
      englishField: 'hospital_address',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 4,
      chineseField: '儲備醫院行政區',
      englishField: 'hospital_city',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '縣市政府',
    },
    {
      id: 5,
      chineseField: '儲備醫院鄉鎮市區別',
      englishField: 'hospital_town',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 6,
      chineseField: '儲備醫院村里別',
      englishField: 'hospital_village',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 7,
      chineseField: '儲備醫院y坐標',
      englishField: 'hospital_y',
      dataType: '所有單位',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 8,
      chineseField: '儲備醫院x坐標',
      englishField: 'hospital_x',
      dataType: '所有單位',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 9,
      chineseField: '儲備醫院動員等級',
      englishField: 'hospital_level',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 10,
      chineseField: '需求類別',
      englishField: 'requirement_type',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 50,
      remark:
        '【必填】\n【BI】儀表板-編管類別分析：\n【戰略物資】：四大體系所屬醫院戰備藥物儲備情況\n【重要物資】：藥品醫材儲備動員管制',
    },
    {
      id: 11,
      chineseField: '品項類別',
      englishField: 'items_type',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 50,
      remark: '藥品、醫材',
    },
    {
      id: 12,
      chineseField: '品項',
      englishField: 'items',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 100,
      remark: '【必填】\n編管品項名稱',
    },
    {
      id: 13,
      chineseField: '計量單位',
      englishField: 'unit',
      dataType: '物資項量',
      type: 'nvarchar',
      length: 50,
      remark: '',
    },
    {
      id: 14,
      chineseField: '編管數量',
      englishField: 'manage_quality',
      dataType: '物資項量',
      type: 'decimal',
      length: '18,6',
      remark: '【必填】阿拉伯數字',
    },
    {
      id: 15,
      chineseField: '通報數量',
      englishField: 'inform_quality',
      dataType: '物資項量',
      type: 'decimal',
      length: '18,6',
      remark: '【必填】阿拉伯數字',
    },
    {
      id: 16,
      chineseField: '通報週期',
      englishField: 'inform_date',
      dataType: '物資項量',
      type: 'datetime',
      length: '',
      remark: '資料異動時間',
    },
    {
      id: '【以下資料由後備指揮部另檔提供】',
      chineseField: '',
      englishField: '',
      dataType: '',
      type: '',
      length: '',
      remark: '',
    },
    {
      id: 17,
      chineseField: '儲備醫院名稱',
      englishField: 'levy_hospital',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 18,
      chineseField: '徵購類別',
      englishField: 'levy_type',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】',
    },
    {
      id: 19,
      chineseField: '徵用機關',
      englishField: 'levy_unit',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 20,
      chineseField: '徵購地點',
      englishField: 'levy_place',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 21,
      chineseField: '徵購縣市別',
      englishField: 'levy_city',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 22,
      chineseField: '徵購鄉鎮市區別',
      englishField: 'levy_town',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 23,
      chineseField: '徵購村里別',
      englishField: 'levy_village',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 24,
      chineseField: '徵購y坐標',
      englishField: 'levy_y',
      dataType: '徵購徵用',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 25,
      chineseField: '徵購x坐標',
      englishField: 'levy_x',
      dataType: '徵購徵用',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 26,
      chineseField: '徵購時間',
      englishField: 'levy_date',
      dataType: '徵購徵用',
      type: 'datetime',
      length: '',
      remark: '民國年7碼',
    },
    {
      id: 27,
      chineseField: '簽證品項',
      englishField: 'visitems',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 100,
      remark: '【必填】',
    },
    {
      id: 28,
      chineseField: '簽證數量',
      englishField: 'visaquantity',
      dataType: '徵購徵用',
      type: 'decimal',
      length: '18,6',
      remark: '【必填】阿拉伯數字',
    },
    {
      id: 29,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 30,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 31,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 32,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 33,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 34,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 35,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 36,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 37,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 38,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frMedicineConfig;
