import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frBusinessShipConfig = new BraidingItem({
  id: 18,
  code: '012',
  name: '商用船舶',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '交通動員方案',
  mobilizationPlanId: 2,
  mobilizationClassification: '水運',
  mobilizationClassificationId: 12,
  firstLevelAgency: '交通部',
  firstLevelAgencyId: '',
  secondaryAgency: '航港局',
  secondaryAgencyId: '',

  searchKey: 'companyName',

  fetchDetailData: (id) => ApiService.frBusinessShip.readFrBusinessShipById(id),
  fetchCategoryData: ApiService.frBusinessShip.readFrBusinessShipPagination,
  queryCategoryData:
    ApiService.frBusinessShip.readFrBusinessShipQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '代表(所有)人',
      keyList: [
        new KeyListItem({ key: 'name', keyTitle: '姓名' }),
        new KeyListItem({ key: 'birthdate', keyTitle: '出生年月日' }),
        new KeyListItem({ key: 'gender', keyTitle: '性別' }),
        new KeyListItem({ key: 'pid', keyTitle: '身分證字號' }),
        new KeyListItem({ key: 'abode', keyTitle: '居住所' }),
        new KeyListItem({ key: 'abodeCity', keyTitle: '居住縣市別' }),
        new KeyListItem({ key: 'abodeTown', keyTitle: '居住鄉鎮市區別' }),
        new KeyListItem({ key: 'abodeVillage', keyTitle: '居住村里別' }),
        new KeyListItem({ key: 'tel', keyTitle: '聯絡電話' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '所有單位',
      keyList: [
        new KeyListItem({ key: 'companyName', keyTitle: '公司名稱' }),
        new KeyListItem({ key: 'companyAddress', keyTitle: '公司地址' }),
        new KeyListItem({ key: 'companyCity', keyTitle: '公司縣市別' }),
        new KeyListItem({ key: 'companyTown', keyTitle: '公司鄉鎮市區別' }),
        new KeyListItem({ key: 'companyVillage', keyTitle: '公司村里別' }),
        new KeyListItem({ key: 'companyTel', keyTitle: '公司聯絡電話' }),
        new KeyListItem({ key: 'shipCenter', keyTitle: '轄管航務中心' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '機具資訊',
      keyList: [
        new KeyListItem({ key: 'shipType', keyTitle: '船舶種類' }),
        new KeyListItem({ key: 'shipName', keyTitle: '船名' }),
        new KeyListItem({ key: 'shipno', keyTitle: '船舶號數' }),
        new KeyListItem({
          key: 'waterBusinessno',
          keyTitle: '水上行動業務識別碼',
        }),
        new KeyListItem({ key: 'shipMaterial', keyTitle: '船舶材質' }),
        new KeyListItem({ key: 'totalweight', keyTitle: '總噸位' }),
        new KeyListItem({ key: 'maxPassenger', keyTitle: '最大載客人數' }),
        new KeyListItem({ key: 'maxWeight', keyTitle: '最大載貨重量' }),
        new KeyListItem({ key: 'totallength', keyTitle: '總長度' }),
        new KeyListItem({ key: 'shipLength', keyTitle: '船長' }),
        new KeyListItem({ key: 'shipWidth', keyTitle: '船寬' }),
        new KeyListItem({ key: 'fullLoad', keyTitle: '滿載吃水' }),
        new KeyListItem({ key: 'maxspeed', keyTitle: '最大航速' }),
        new KeyListItem({ key: 'rate', keyTitle: '航行速率' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '徵購徵用',
      keyList: [
        new KeyListItem({ key: 'deputyname', keyTitle: '代表人(所有人)姓名' }),
        new KeyListItem({ key: 'deputyid', keyTitle: '身分證字號' }),
        new KeyListItem({ key: 'levyType', keyTitle: '徵用類別' }),
        new KeyListItem({ key: 'levyUnit', keyTitle: '徵用機關' }),
        new KeyListItem({ key: 'levyPlace', keyTitle: '徵用地點' }),
        new KeyListItem({ key: 'levyCity', keyTitle: '徵用縣市別' }),
        new KeyListItem({ key: 'levyTown', keyTitle: '徵用鄉鎮市區別' }),
        new KeyListItem({ key: 'levyVillage', keyTitle: '徵用村里別' }),
        new KeyListItem({ key: 'levyTime', keyTitle: '徵用時間' }),
        new KeyListItem({ key: 'levyShiptype', keyTitle: '船舶種類' }),
        new KeyListItem({ key: 'levyShipno', keyTitle: '船舶號數' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '公司名稱',
      accessor: 'companyName',
    },
    {
      Header: '公司地址',
      accessor: 'companyAddress',
    },
    {
      Header: '船舶號數',
      accessor: 'shipno',
    },
    {
      Header: '水上行動業務識別碼',
      accessor: 'waterBusinessno',
    },
    {
      Header: '船舶材質',
      accessor: 'shipMaterial',
    },
    {
      Header: '徵用機關',
      accessor: 'levyUnit',
    },
    {
      Header: '徵用地點',
      accessor: 'levyPlace',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '姓名',
      englishField: 'name',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark:
        '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 3,
      chineseField: '出生年月日',
      englishField: 'birthdate',
      dataType: '代表(所有)人',
      type: 'datetime',
      length: '',
      remark: '民國年7碼',
    },
    {
      id: 4,
      chineseField: '性別',
      englishField: 'gender',
      dataType: '代表(所有)人',
      type: 'int',
      length: '',
      remark: '性別判斷依身分證第二碼判斷：1、8為男性、2、9為女性',
    },
    {
      id: 5,
      chineseField: '身分證字號',
      englishField: 'pid',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 20,
      remark:
        '【非必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.僅可輸入國人身分證字號及外僑統一證號',
    },
    {
      id: 6,
      chineseField: '居住所',
      englishField: 'abode',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '完整地址',
    },
    {
      id: 7,
      chineseField: '居住縣市別',
      englishField: 'abode_city',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 8,
      chineseField: '居住鄉鎮市區別',
      englishField: 'abode_town',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 9,
      chineseField: '居住村里別',
      englishField: 'abode_village',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 10,
      chineseField: '居住y坐標',
      englishField: 'abode_y',
      dataType: '代表(所有)人',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 11,
      chineseField: '居住x坐標',
      englishField: 'abode_x',
      dataType: '代表(所有)人',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 12,
      chineseField: '聯絡電話',
      englishField: 'tel',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 30,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 13,
      chineseField: '公司名稱',
      englishField: 'company_name',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 200,
      remark: '',
    },
    {
      id: 14,
      chineseField: '公司地址',
      englishField: 'company_address',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】',
    },
    {
      id: 15,
      chineseField: '公司縣市別',
      englishField: 'company_city',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別\nBI規則：縣市別資料順序(船籍港、公司地址)',
    },
    {
      id: 16,
      chineseField: '公司鄉鎮市區別',
      englishField: 'company_town',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別\nBI規則：縣市別資料順序(船籍港、公司地址)',
    },
    {
      id: 17,
      chineseField: '公司村里別',
      englishField: 'company_village',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 18,
      chineseField: '公司y坐標',
      englishField: 'company_y',
      dataType: '所有單位',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 19,
      chineseField: '公司x坐標',
      englishField: 'company_x',
      dataType: '所有單位',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 20,
      chineseField: '公司聯絡電話',
      englishField: 'company_tel',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 30,
      remark: '',
    },
    {
      id: 21,
      chineseField: '轄管航務中心',
      englishField: 'ship_center',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 22,
      chineseField: '船舶種類',
      englishField: 'ship_type',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】',
    },
    {
      id: 23,
      chineseField: '船名',
      englishField: 'ship_name',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 30,
      remark: '',
    },
    {
      id: 24,
      chineseField: '船籍港',
      englishField: 'ship_address',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】港口名稱\nBI規則：縣市別資料順序(船籍港、公司地址)',
    },
    {
      id: 25,
      chineseField: '船舶號數',
      englishField: 'shipno',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】',
    },
    {
      id: 26,
      chineseField: '水上行動業務識別碼',
      englishField: 'water_businessno',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 30,
      remark: '',
    },
    {
      id: 27,
      chineseField: '船舶材質',
      englishField: 'ship_material',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 30,
      remark: '',
    },
    {
      id: 28,
      chineseField: '總噸位',
      englishField: 'totalweight',
      dataType: '機具資訊',
      type: 'decimal',
      length: '18,6',
      remark: '',
    },
    {
      id: 29,
      chineseField: '最大載客人數',
      englishField: 'max_passenger',
      dataType: '機具資訊',
      type: 'int',
      length: '',
      remark: '',
    },
    {
      id: 30,
      chineseField: '最大載貨重量',
      englishField: 'max_weight',
      dataType: '機具資訊',
      type: 'decimal',
      length: '18,6',
      remark: '載重噸位',
    },
    {
      id: 31,
      chineseField: '總長度',
      englishField: 'totallength',
      dataType: '機具資訊',
      type: 'decimal',
      length: '18,6',
      remark: '公尺',
    },
    {
      id: 32,
      chineseField: '船長',
      englishField: 'ship_length',
      dataType: '機具資訊',
      type: 'decimal',
      length: '18,6',
      remark: '公尺',
    },
    {
      id: 33,
      chineseField: '船寬',
      englishField: 'ship_width',
      dataType: '機具資訊',
      type: 'decimal',
      length: '18,6',
      remark: '公尺',
    },
    {
      id: 34,
      chineseField: '滿載吃水',
      englishField: 'full_load',
      dataType: '機具資訊',
      type: 'decimal',
      length: '18,6',
      remark: '公尺',
    },
    {
      id: 35,
      chineseField: '最大航速',
      englishField: 'maxspeed',
      dataType: '機具資訊',
      type: 'decimal',
      length: '18,6',
      remark: '節',
    },
    {
      id: 36,
      chineseField: '航行速率',
      englishField: 'rate',
      dataType: '機具資訊',
      type: 'decimal',
      length: '18,6',
      remark: '節',
    },
    {
      id: '【以下資料由後備指揮部另檔提供】',
      chineseField: '',
      englishField: '',
      dataType: '',
      type: '',
      length: '',
      remark: '',
    },
    {
      id: 37,
      chineseField: '徵用類別',
      englishField: 'levy_type',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】',
    },
    {
      id: 38,
      chineseField: '徵用機關',
      englishField: 'levy_unit',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 39,
      chineseField: '徵用地點',
      englishField: 'levy_place',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 40,
      chineseField: '徵用縣市別',
      englishField: 'levy_city',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 41,
      chineseField: '徵用鄉鎮市區別',
      englishField: 'levy_town',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 42,
      chineseField: '徵用村里別',
      englishField: 'levy_village',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 43,
      chineseField: '徵用y坐標',
      englishField: 'levy_y',
      dataType: '徵購徵用',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 44,
      chineseField: '徵用x坐標',
      englishField: 'levy_x',
      dataType: '徵購徵用',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 45,
      chineseField: '徵用時間',
      englishField: 'levy_time',
      dataType: '徵購徵用',
      type: 'datetime',
      length: '',
      remark: '民國年7碼',
    },
    {
      id: 46,
      chineseField: '徵用船舶號數',
      englishField: 'levy_shipno',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】\n人機併徵勾稽欄位',
    },
    {
      id: 47,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 48,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 49,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 50,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 51,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 52,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 53,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 54,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 55,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 56,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frBusinessShipConfig;
