import BraidingItem from '../baseModels/BraidingItem';
import ConfigListItem from '../baseModels/ConfigListItem';
import KeyListItem from '../baseModels/KeyListItem';

import ApiService from '../../../api/ApiService';

const frHeavymachineryConfig = new BraidingItem({
  id: 26,
  code: '018',
  name: '工程重機械',
  type: '物力',
  typeIndex: '2',
  mobilizationPlan: '交通動員方案',
  mobilizationPlanId: 2,
  mobilizationClassification: '工程重機械',
  mobilizationClassificationId: 17,
  firstLevelAgency: '內政部',
  firstLevelAgencyId: '',
  secondaryAgency: '國土署',
  secondaryAgencyId: '',

  searchKey: 'companyName',

  fetchDetailData: (id) =>
    ApiService.frHeavymachinery.readFrHeavymachineryById(id),
  fetchCategoryData: ApiService.frHeavymachinery.readFrHeavymachineryPagination,
  queryCategoryData:
    ApiService.frHeavymachinery.readFrHeavymachineryQueryPagination,

  configList: [
    new ConfigListItem({
      sectionTitle: '代表(所有)人',
      keyList: [
        new KeyListItem({ key: 'name', keyTitle: '姓名' }),
        new KeyListItem({ key: 'birthdate', keyTitle: '出生年月日' }),
        new KeyListItem({ key: 'age', keyTitle: '年齡' }),
        new KeyListItem({ key: 'pid', keyTitle: '身分證字號' }),
        new KeyListItem({ key: 'gender', keyTitle: '性別' }),
        new KeyListItem({ key: 'abode', keyTitle: '居住所' }),
        new KeyListItem({ key: 'abodeCity', keyTitle: '居住縣市別' }),
        new KeyListItem({ key: 'abodeTown', keyTitle: '居住鄉鎮市區別' }),
        new KeyListItem({ key: 'abodeVillage', keyTitle: '居住村里別' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '所有單位',
      keyList: [
        new KeyListItem({ key: 'tel', keyTitle: '聯絡電話' }),
        new KeyListItem({ key: 'companyName', keyTitle: '公司名稱' }),
        new KeyListItem({ key: 'companyAddress', keyTitle: '公司地址' }),
        new KeyListItem({ key: 'companyCity', keyTitle: '公司縣市別' }),
        new KeyListItem({ key: 'companyTown', keyTitle: '公司鄉鎮市區別' }),
        new KeyListItem({ key: 'companyVillage', keyTitle: '公司村里別' }),
        new KeyListItem({ key: 'hmachineryCity', keyTitle: '機具縣市別' }),
        new KeyListItem({ key: 'hmachineryTown', keyTitle: '機具鄉鎮市區別' }),
        new KeyListItem({ key: 'hmachineryVillage', keyTitle: '機具村里別' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '機具資訊',
      keyList: [
        new KeyListItem({ key: 'hmachineryType', keyTitle: '重機械類別' }),
        new KeyListItem({
          key: 'hmachineryModel',
          keyTitle: '機具種類型號或規格',
        }),
        new KeyListItem({ key: 'hmachineryMove', keyTitle: '移動方式' }),
        new KeyListItem({ key: 'hmachineryId', keyTitle: '唯一序號' }),
        new KeyListItem({ key: 'hmachineryAddress', keyTitle: '機具所在地址' }),
      ],
    }),
    new ConfigListItem({
      sectionTitle: '徵購徵用',
      keyList: [
        new KeyListItem({ key: 'deputyname', keyTitle: '代表人(所有人)姓名' }),
        new KeyListItem({ key: 'deputyid', keyTitle: '身分證字號' }),
        new KeyListItem({ key: 'levyType', keyTitle: '徵用類別' }),
        new KeyListItem({ key: 'levyUnit', keyTitle: '徵用機關' }),
        new KeyListItem({ key: 'levyPlace', keyTitle: '徵用地點' }),
        new KeyListItem({ key: 'levyCity', keyTitle: '徵用縣市別' }),
        new KeyListItem({ key: 'levyTown', keyTitle: '徵用鄉鎮市區別' }),
        new KeyListItem({ key: 'levyVillage', keyTitle: '徵用村里別' }),
        new KeyListItem({ key: 'levyTime', keyTitle: '徵用時間' }),
        new KeyListItem({ key: 'levyModel', keyTitle: '車輛型號或規格' }),
        new KeyListItem({ key: 'visaquantity', keyTitle: '簽證數量' }),
      ],
    }),
  ],
  planConfigList: [],
  categoryTableHeader: [
    {
      Header: '公司名稱',
      accessor: 'companyName',
    },
    {
      Header: '公司地址',
      accessor: 'companyAddress',
    },
    {
      Header: '徵用機關',
      accessor: 'levyUnit',
    },
    {
      Header: '徵用地點',
      accessor: 'levyPlace',
    },
  ],
  criteriaList: [
    {
      id: 1,
      chineseField: '序號',
      englishField: 'id',
      dataType: '',
      type: 'int',
      length: '',
      remark: 'PK',
    },
    {
      id: 2,
      chineseField: '姓名',
      englishField: 'name',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark:
        '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽\n3.可輸入英文、羅馬拼音、小數點\n4.原住民特殊符號',
    },
    {
      id: 3,
      chineseField: '出生年月日',
      englishField: 'birthdate',
      dataType: '代表(所有)人',
      type: 'datetime',
      length: '',
      remark: '民國年7碼',
    },
    {
      id: 4,
      chineseField: '性別',
      englishField: 'gender',
      dataType: '代表(所有)人',
      type: 'int',
      length: '',
      remark: '性別判斷依身分證第二碼判斷：1、8為男性、2、9為女性',
    },
    {
      id: 5,
      chineseField: '身分證字號',
      englishField: 'pid',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 20,
      remark:
        '【必填】完整不遮蔽\n1.來源資料供系統比對運用\n2.系統資料查詢採半遮蔽',
    },
    {
      id: 6,
      chineseField: '居住所',
      englishField: 'abode',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 200,
      remark: '完整地址',
    },
    {
      id: 7,
      chineseField: '居住縣市別',
      englishField: 'abode_city',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 8,
      chineseField: '居住鄉鎮市區別',
      englishField: 'abode_town',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 9,
      chineseField: '居住村里別',
      englishField: 'abode_village',
      dataType: '代表(所有)人',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 10,
      chineseField: '居住y坐標',
      englishField: 'abode_y',
      dataType: '代表(所有)人',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 11,
      chineseField: '居住x坐標',
      englishField: 'abode_x',
      dataType: '代表(所有)人',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 12,
      chineseField: '聯絡電話',
      englishField: 'tel',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 30,
      remark: '有線電話或行動電話均可',
    },
    {
      id: 13,
      chineseField: '公司名稱',
      englishField: 'company_name',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 50,
      remark: '',
    },
    {
      id: 14,
      chineseField: '公司所在地址',
      englishField: 'company_address',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 200,
      remark: '完整地址',
    },
    {
      id: 15,
      chineseField: '公司縣市別',
      englishField: 'company_city',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 16,
      chineseField: '公司鄉鎮市區別',
      englishField: 'company_town',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 17,
      chineseField: '公司村里別',
      englishField: 'company_village',
      dataType: '所有單位',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 18,
      chineseField: '公司y坐標',
      englishField: 'company_y',
      dataType: '所有單位',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 19,
      chineseField: '公司x坐標',
      englishField: 'company_x',
      dataType: '所有單位',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 20,
      chineseField: '重機械類別',
      englishField: 'hmachinery_type',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 30,
      remark: '【必填】',
    },
    {
      id: 21,
      chineseField: '移動方式',
      englishField: 'hmachinery_move',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 22,
      chineseField: '唯一序號',
      englishField: 'hmachinery_id',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 20,
      remark: '【必填】',
    },
    {
      id: 23,
      chineseField: '機具種類型號或規格',
      englishField: 'hmachinery_model',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 50,
      remark: '',
    },
    {
      id: 24,
      chineseField: '機具所在地址',
      englishField: 'hmachinery_address',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 25,
      chineseField: '機具縣市別',
      englishField: 'hmachinery_city',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 26,
      chineseField: '機具鄉鎮市區別',
      englishField: 'hmachinery_town',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 27,
      chineseField: '機具村里別',
      englishField: 'hmachinery_village',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 28,
      chineseField: '機具y坐標',
      englishField: 'hmachinery_y',
      dataType: '機具資訊',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 29,
      chineseField: '機具x坐標',
      englishField: 'hmachinery_x',
      dataType: '機具資訊',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: '【以下資料由後備指揮部另檔提供】',
      chineseField: '',
      englishField: '',
      dataType: '',
      type: '',
      length: '',
      remark: '',
    },
    {
      id: 30,
      chineseField: '徵用類別',
      englishField: 'levy_type',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 31,
      chineseField: '徵用機關',
      englishField: 'levy_unit',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 32,
      chineseField: '徵用地點',
      englishField: 'levy_place',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 200,
      remark: '【必填】完整地址',
    },
    {
      id: 33,
      chineseField: '徵用縣市別',
      englishField: 'levy_city',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '直轄市、縣市別',
    },
    {
      id: 34,
      chineseField: '徵用鄉鎮市區別',
      englishField: 'levy_town',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '鄉鎮市區別',
    },
    {
      id: 35,
      chineseField: '徵用村里別',
      englishField: 'levy_village',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 10,
      remark: '村里別',
    },
    {
      id: 36,
      chineseField: '徵用y坐標',
      englishField: 'levy_y',
      dataType: '徵購徵用',
      type: 'decimal',
      length: '9,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 37,
      chineseField: '徵用x坐標',
      englishField: 'levy_x',
      dataType: '徵購徵用',
      type: 'decimal',
      length: '10,6',
      remark: '編管機關毋須填寫',
    },
    {
      id: 38,
      chineseField: '徵用時間',
      englishField: 'levy_time',
      dataType: '徵購徵用',
      type: 'datetime',
      length: '',
      remark: '民國年7碼',
    },
    {
      id: 39,
      chineseField: '徵用重機械類別',
      englishField: 'levy_model',
      dataType: '徵購徵用',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 40,
      chineseField: '徵用移動方式',
      englishField: 'levy_hmachinery_move',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 50,
      remark: '【必填】',
    },
    {
      id: 41,
      chineseField: '徵用唯一序號',
      englishField: 'levy_hmachinery_id',
      dataType: '機具資訊',
      type: 'nvarchar',
      length: 20,
      remark: '【必填】',
    },
    {
      id: 42,
      chineseField: '新增人員',
      englishField: 'cre_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 43,
      chineseField: '新增日期',
      englishField: 'cre_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 44,
      chineseField: '修改人員',
      englishField: 'update_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 45,
      chineseField: '修改日期',
      englishField: 'update_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 46,
      chineseField: '傳輸人員',
      englishField: 'upload_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 47,
      chineseField: '傳輸日期',
      englishField: 'upload_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
    {
      id: 48,
      chineseField: '資料狀態',
      englishField: 'data_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.暫存狀態\n2.正式狀態\n3.已傳送',
    },
    {
      id: 49,
      chineseField: '審認狀態',
      englishField: 'approval_status',
      dataType: '',
      type: 'nvarchar',
      length: 10,
      remark: '編管機關毋須填寫\n1.已審認\n2.未審認',
    },
    {
      id: 50,
      chineseField: '審認人員',
      englishField: 'approval_user',
      dataType: '',
      type: 'nvarchar',
      length: 30,
      remark: '編管機關毋須填寫',
    },
    {
      id: 51,
      chineseField: '審認日期',
      englishField: 'approval_date',
      dataType: '',
      type: 'datetime',
      length: '',
      remark: '編管機關毋須填寫',
    },
  ],
});

export default frHeavymachineryConfig;
